// seedLab.js
// Karnataka Outside Labs Seed Data
// 30 Districts × 10 Labs = 300 Total Labs
// All labs are independent/outside diagnostic centers (NOT hospital labs)

const labs = [
  // ─────────────────────────────────────────
  // 1. BENGALURU URBAN
  // ─────────────────────────────────────────
  {
    name: "Thyrocare Diagnostics",
    district: "Bengaluru Urban",
    address: "MG Road, Bengaluru",
    phone: "9880100001",
    type: "outside",
    pincode: "560001",
    services: ["Blood Test", "Urine Test", "Thyroid Profile"],
  },
  {
    name: "SRL Diagnostics",
    district: "Bengaluru Urban",
    address: "Jayanagar, Bengaluru",
    phone: "9880100002",
    type: "outside",
    pincode: "560011",
    services: ["CBC", "Lipid Profile", "Liver Function"],
  },
  {
    name: "Metropolis Healthcare",
    district: "Bengaluru Urban",
    address: "Koramangala, Bengaluru",
    phone: "9880100003",
    type: "outside",
    pincode: "560034",
    services: ["HbA1c", "Kidney Function", "Vitamin D"],
  },
  {
    name: "Neuberg Diagnostics",
    district: "Bengaluru Urban",
    address: "Indiranagar, Bengaluru",
    phone: "9880100004",
    type: "outside",
    pincode: "560038",
    services: ["PCR Test", "Culture & Sensitivity", "Biopsy"],
  },
  {
    name: "Vijaya Diagnostic Centre",
    district: "Bengaluru Urban",
    address: "Rajajinagar, Bengaluru",
    phone: "9880100005",
    type: "outside",
    pincode: "560010",
    services: ["X-Ray", "ECG", "Blood Sugar"],
  },
  {
    name: "Agilus Diagnostics",
    district: "Bengaluru Urban",
    address: "Whitefield, Bengaluru",
    phone: "9880100006",
    type: "outside",
    pincode: "560066",
    services: ["MRI", "CT Scan", "PET Scan"],
  },
  {
    name: "Healthians Lab",
    district: "Bengaluru Urban",
    address: "Electronic City, Bengaluru",
    phone: "9880100007",
    type: "outside",
    pincode: "560100",
    services: ["Full Body Checkup", "Diabetes Panel"],
  },
  {
    name: "Dr Lal PathLabs",
    district: "Bengaluru Urban",
    address: "Marathahalli, Bengaluru",
    phone: "9880100008",
    type: "outside",
    pincode: "560037",
    services: ["Hormonal Assay", "STI Panel", "Iron Studies"],
  },
  {
    name: "Redcliffe Labs",
    district: "Bengaluru Urban",
    address: "HSR Layout, Bengaluru",
    phone: "9880100009",
    type: "outside",
    pincode: "560102",
    services: ["COVID Antibody", "Allergy Panel", "CBC"],
  },
  {
    name: "Star Imaging & Path Lab",
    district: "Bengaluru Urban",
    address: "BTM Layout, Bengaluru",
    phone: "9880100010",
    type: "outside",
    pincode: "560029",
    services: ["Ultrasound", "Doppler", "Mammography"],
  },

  // ─────────────────────────────────────────
  // 2. BENGALURU RURAL
  // ─────────────────────────────────────────
  {
    name: "Aarogya Diagnostics",
    district: "Bengaluru Rural",
    address: "Devanahalli, Bengaluru Rural",
    phone: "9880200001",
    type: "outside",
    pincode: "562110",
    services: ["Blood Test", "Urine Analysis"],
  },
  {
    name: "Namma Lab",
    district: "Bengaluru Rural",
    address: "Doddaballapura, Bengaluru Rural",
    phone: "9880200002",
    type: "outside",
    pincode: "561203",
    services: ["Thyroid", "Liver Function", "CBC"],
  },
  {
    name: "Sri Sai Diagnostics",
    district: "Bengaluru Rural",
    address: "Hoskote, Bengaluru Rural",
    phone: "9880200003",
    type: "outside",
    pincode: "562114",
    services: ["X-Ray", "ECG", "Blood Sugar"],
  },
  {
    name: "Suraksha Diagnostic Centre",
    district: "Bengaluru Rural",
    address: "Nelamangala, Bengaluru Rural",
    phone: "9880200004",
    type: "outside",
    pincode: "562123",
    services: ["Lipid Profile", "Urine Culture"],
  },
  {
    name: "Arogyadham Lab",
    district: "Bengaluru Rural",
    address: "Ramanagara, Bengaluru Rural",
    phone: "9880200005",
    type: "outside",
    pincode: "562159",
    services: ["HbA1c", "Kidney Function"],
  },
  {
    name: "Jeevan Jyothi Lab",
    district: "Bengaluru Rural",
    address: "Channapatna, Bengaluru Rural",
    phone: "9880200006",
    type: "outside",
    pincode: "571501",
    services: ["Malaria Test", "Dengue NS1", "CBC"],
  },
  {
    name: "Health Point Diagnostics",
    district: "Bengaluru Rural",
    address: "Magadi, Bengaluru Rural",
    phone: "9880200007",
    type: "outside",
    pincode: "562120",
    services: ["Blood Group", "Widal Test"],
  },
  {
    name: "Veda Diagnostics",
    district: "Bengaluru Rural",
    address: "Kanakapura, Bengaluru Rural",
    phone: "9880200008",
    type: "outside",
    pincode: "562117",
    services: ["Pap Smear", "Hormone Panel"],
  },
  {
    name: "Divine Lab Centre",
    district: "Bengaluru Rural",
    address: "Anekal, Bengaluru Rural",
    phone: "9880200009",
    type: "outside",
    pincode: "562106",
    services: ["Stool Test", "Sputum AFB"],
  },
  {
    name: "Swastha Diagnostic Lab",
    district: "Bengaluru Rural",
    address: "Kudur, Bengaluru Rural",
    phone: "9880200010",
    type: "outside",
    pincode: "562126",
    services: ["Ultrasound", "Full Body Checkup"],
  },

  // ─────────────────────────────────────────
  // 3. MYSURU
  // ─────────────────────────────────────────
  {
    name: "Thyrocare Mysuru",
    district: "Mysuru",
    address: "Saraswathipuram, Mysuru",
    phone: "9880300001",
    type: "outside",
    pincode: "570009",
    services: ["Thyroid", "CBC", "Blood Sugar"],
  },
  {
    name: "SRL Diagnostics Mysuru",
    district: "Mysuru",
    address: "Vijayanagar, Mysuru",
    phone: "9880300002",
    type: "outside",
    pincode: "570017",
    services: ["Lipid Profile", "Liver Function"],
  },
  {
    name: "Vijaya Lab",
    district: "Mysuru",
    address: "Kuvempunagar, Mysuru",
    phone: "9880300003",
    type: "outside",
    pincode: "570023",
    services: ["Kidney Function", "Vitamin D", "Iron"],
  },
  {
    name: "Mysore Diagnostic Centre",
    district: "Mysuru",
    address: "Lashkar Mohalla, Mysuru",
    phone: "9880300004",
    type: "outside",
    pincode: "570001",
    services: ["X-Ray", "ECG", "Ultrasound"],
  },
  {
    name: "Care Diagnostics Mysuru",
    district: "Mysuru",
    address: "Hebbal, Mysuru",
    phone: "9880300005",
    type: "outside",
    pincode: "570016",
    services: ["Full Body Checkup", "Diabetes Panel"],
  },
  {
    name: "Dr Lal PathLabs Mysuru",
    district: "Mysuru",
    address: "Chamundipuram, Mysuru",
    phone: "9880300006",
    type: "outside",
    pincode: "570004",
    services: ["Allergy Panel", "HbA1c"],
  },
  {
    name: "Health Map Lab",
    district: "Mysuru",
    address: "Nazarbad, Mysuru",
    phone: "9880300007",
    type: "outside",
    pincode: "570010",
    services: ["PCR", "COVID Test", "Blood Culture"],
  },
  {
    name: "Nrupathunga Diagnostics",
    district: "Mysuru",
    address: "Mandi Mohalla, Mysuru",
    phone: "9880300008",
    type: "outside",
    pincode: "570021",
    services: ["Pap Smear", "Hormonal Test"],
  },
  {
    name: "Arogyaseva Lab",
    district: "Mysuru",
    address: "Bogadi, Mysuru",
    phone: "9880300009",
    type: "outside",
    pincode: "570026",
    services: ["Stool Test", "Widal Test"],
  },
  {
    name: "Metropolis Mysuru",
    district: "Mysuru",
    address: "Gokulam, Mysuru",
    phone: "9880300010",
    type: "outside",
    pincode: "570002",
    services: ["MRI", "CT Scan", "PET Scan"],
  },

  // ─────────────────────────────────────────
  // 4. TUMAKURU
  // ─────────────────────────────────────────
  {
    name: "Srinivasa Diagnostic Lab",
    district: "Tumakuru",
    address: "BH Road, Tumakuru",
    phone: "9880400001",
    type: "outside",
    pincode: "572101",
    services: ["CBC", "Urine Test", "Blood Sugar"],
  },
  {
    name: "Siddaganga Diagnostics",
    district: "Tumakuru",
    address: "Siddaganga Road, Tumakuru",
    phone: "9880400002",
    type: "outside",
    pincode: "572102",
    services: ["Thyroid", "Lipid Profile"],
  },
  {
    name: "City Diagnostic Centre",
    district: "Tumakuru",
    address: "Ashoka Road, Tumakuru",
    phone: "9880400003",
    type: "outside",
    pincode: "572103",
    services: ["X-Ray", "ECG"],
  },
  {
    name: "Akash Lab",
    district: "Tumakuru",
    address: "Tiptur, Tumakuru",
    phone: "9880400004",
    type: "outside",
    pincode: "572201",
    services: ["Dengue", "Malaria", "CBC"],
  },
  {
    name: "Poornima Diagnostics",
    district: "Tumakuru",
    address: "Gubbi, Tumakuru",
    phone: "9880400005",
    type: "outside",
    pincode: "572216",
    services: ["Kidney Function", "Liver Function"],
  },
  {
    name: "Narayana Diagnostics",
    district: "Tumakuru",
    address: "Koratagere, Tumakuru",
    phone: "9880400006",
    type: "outside",
    pincode: "572129",
    services: ["HbA1c", "Full Body Checkup"],
  },
  {
    name: "Shree Lab Centre",
    district: "Tumakuru",
    address: "Madhugiri, Tumakuru",
    phone: "9880400007",
    type: "outside",
    pincode: "572132",
    services: ["Allergy Panel", "Vitamin D"],
  },
  {
    name: "Janatha Diagnostic Lab",
    district: "Tumakuru",
    address: "Pavagada, Tumakuru",
    phone: "9880400008",
    type: "outside",
    pincode: "561202",
    services: ["Blood Culture", "Sputum Test"],
  },
  {
    name: "Pushpa Lab Centre",
    district: "Tumakuru",
    address: "Turuvekere, Tumakuru",
    phone: "9880400009",
    type: "outside",
    pincode: "572227",
    services: ["Pap Smear", "Ultrasound"],
  },
  {
    name: "Sahyadri Diagnostics",
    district: "Tumakuru",
    address: "Chikkanayakanahalli, Tumakuru",
    phone: "9880400010",
    type: "outside",
    pincode: "572214",
    services: ["Stool Test", "Widal Test"],
  },

  // ─────────────────────────────────────────
  // 5. HASSAN
  // ─────────────────────────────────────────
  {
    name: "Hassan Diagnostic Centre",
    district: "Hassan",
    address: "BM Road, Hassan",
    phone: "9880500001",
    type: "outside",
    pincode: "573201",
    services: ["CBC", "Blood Sugar", "ECG"],
  },
  {
    name: "Cauvery Lab Hassan",
    district: "Hassan",
    address: "Santepete, Hassan",
    phone: "9880500002",
    type: "outside",
    pincode: "573201",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Arogya Lab",
    district: "Hassan",
    address: "Arsikere, Hassan",
    phone: "9880500003",
    type: "outside",
    pincode: "573103",
    services: ["Lipid Profile", "Kidney Function"],
  },
  {
    name: "Nethra Diagnostics",
    district: "Hassan",
    address: "Belur, Hassan",
    phone: "9880500004",
    type: "outside",
    pincode: "573115",
    services: ["Urine Test", "Stool Test"],
  },
  {
    name: "Prasanna Diagnostic Lab",
    district: "Hassan",
    address: "Channarayapatna, Hassan",
    phone: "9880500005",
    type: "outside",
    pincode: "573116",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Siri Lab Centre",
    district: "Hassan",
    address: "Sakleshpur, Hassan",
    phone: "9880500006",
    type: "outside",
    pincode: "573134",
    services: ["HbA1c", "Dengue"],
  },
  {
    name: "Vighnaharta Lab",
    district: "Hassan",
    address: "Holenarasipur, Hassan",
    phone: "9880500007",
    type: "outside",
    pincode: "573211",
    services: ["Blood Culture", "CBC"],
  },
  {
    name: "Mahalakshmi Diagnostics",
    district: "Hassan",
    address: "Alur, Hassan",
    phone: "9880500008",
    type: "outside",
    pincode: "573213",
    services: ["Full Body Checkup"],
  },
  {
    name: "Gowri Lab Hassan",
    district: "Hassan",
    address: "Manjarabad, Hassan",
    phone: "9880500009",
    type: "outside",
    pincode: "573201",
    services: ["Vitamin D", "Iron Studies"],
  },
  {
    name: "Spandana Lab Centre",
    district: "Hassan",
    address: "Arasikere Road, Hassan",
    phone: "9880500010",
    type: "outside",
    pincode: "573103",
    services: ["Malaria", "Typhoid"],
  },

  // ─────────────────────────────────────────
  // 6. MANDYA
  // ─────────────────────────────────────────
  {
    name: "Mandya Diagnostic Lab",
    district: "Mandya",
    address: "Kasturba Road, Mandya",
    phone: "9880600001",
    type: "outside",
    pincode: "571401",
    services: ["CBC", "Blood Sugar"],
  },
  {
    name: "Suvarna Diagnostics",
    district: "Mandya",
    address: "MUDA Layout, Mandya",
    phone: "9880600002",
    type: "outside",
    pincode: "571401",
    services: ["Thyroid", "Lipid Profile"],
  },
  {
    name: "Kaveri Lab Centre",
    district: "Mandya",
    address: "KR Pet, Mandya",
    phone: "9880600003",
    type: "outside",
    pincode: "571426",
    services: ["Liver Function", "Kidney Function"],
  },
  {
    name: "Mahaveer Diagnostics",
    district: "Mandya",
    address: "Nagamangala, Mandya",
    phone: "9880600004",
    type: "outside",
    pincode: "571432",
    services: ["X-Ray", "ECG"],
  },
  {
    name: "Sanjeevini Lab",
    district: "Mandya",
    address: "Maddur, Mandya",
    phone: "9880600005",
    type: "outside",
    pincode: "571428",
    services: ["Urine Culture", "Stool Test"],
  },
  {
    name: "Vivekananda Diagnostics",
    district: "Mandya",
    address: "Malavalli, Mandya",
    phone: "9880600006",
    type: "outside",
    pincode: "571430",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Siddartha Lab",
    district: "Mandya",
    address: "Srirangapatna, Mandya",
    phone: "9880600007",
    type: "outside",
    pincode: "571438",
    services: ["HbA1c", "Vitamin B12"],
  },
  {
    name: "Pavana Diagnostics",
    district: "Mandya",
    address: "Pandavapura, Mandya",
    phone: "9880600008",
    type: "outside",
    pincode: "571434",
    services: ["Allergy Panel", "Full Body Checkup"],
  },
  {
    name: "Sai Krupa Lab",
    district: "Mandya",
    address: "Kirugavalu, Mandya",
    phone: "9880600009",
    type: "outside",
    pincode: "571431",
    services: ["Blood Culture", "Sputum AFB"],
  },
  {
    name: "Nandana Diagnostic Centre",
    district: "Mandya",
    address: "Shivapura, Mandya",
    phone: "9880600010",
    type: "outside",
    pincode: "571401",
    services: ["Ultrasound", "Mammography"],
  },

  // ─────────────────────────────────────────
  // 7. CHIKKAMAGALURU
  // ─────────────────────────────────────────
  {
    name: "Malnad Diagnostics",
    district: "Chikkamagaluru",
    address: "Coffee Land Road, Chikkamagaluru",
    phone: "9880700001",
    type: "outside",
    pincode: "577101",
    services: ["CBC", "Blood Sugar", "ECG"],
  },
  {
    name: "Bhadra Diagnostic Lab",
    district: "Chikkamagaluru",
    address: "Nehru Road, Chikkamagaluru",
    phone: "9880700002",
    type: "outside",
    pincode: "577101",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Sahyadri Lab Centre",
    district: "Chikkamagaluru",
    address: "Mudigere, Chikkamagaluru",
    phone: "9880700003",
    type: "outside",
    pincode: "577132",
    services: ["Malaria", "Dengue", "Typhoid"],
  },
  {
    name: "Girija Diagnostics",
    district: "Chikkamagaluru",
    address: "Kadur, Chikkamagaluru",
    phone: "9880700004",
    type: "outside",
    pincode: "577548",
    services: ["Kidney Function", "Urine Test"],
  },
  {
    name: "Srinivasa Lab Chikkamagaluru",
    district: "Chikkamagaluru",
    address: "Tarikere, Chikkamagaluru",
    phone: "9880700005",
    type: "outside",
    pincode: "577228",
    services: ["Lipid Profile", "Vitamin D"],
  },
  {
    name: "Hemavathi Diagnostic Centre",
    district: "Chikkamagaluru",
    address: "Birur, Chikkamagaluru",
    phone: "9880700006",
    type: "outside",
    pincode: "577116",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Prajna Lab",
    district: "Chikkamagaluru",
    address: "Koppa, Chikkamagaluru",
    phone: "9880700007",
    type: "outside",
    pincode: "577126",
    services: ["Blood Culture", "Stool Test"],
  },
  {
    name: "Namma Arogya Lab",
    district: "Chikkamagaluru",
    address: "NR Pura, Chikkamagaluru",
    phone: "9880700008",
    type: "outside",
    pincode: "577142",
    services: ["HbA1c", "Full Body Checkup"],
  },
  {
    name: "Green Valley Diagnostics",
    district: "Chikkamagaluru",
    address: "Sringeri, Chikkamagaluru",
    phone: "9880700009",
    type: "outside",
    pincode: "577139",
    services: ["Allergy Panel", "Hormone Panel"],
  },
  {
    name: "Kerehaklu Lab Centre",
    district: "Chikkamagaluru",
    address: "Aldur, Chikkamagaluru",
    phone: "9880700010",
    type: "outside",
    pincode: "577101",
    services: ["Pap Smear", "CBC"],
  },

  // ─────────────────────────────────────────
  // 8. SHIVAMOGGA
  // ─────────────────────────────────────────
  {
    name: "Tunga Diagnostic Centre",
    district: "Shivamogga",
    address: "Vinoba Road, Shivamogga",
    phone: "9880800001",
    type: "outside",
    pincode: "577201",
    services: ["CBC", "Blood Sugar"],
  },
  {
    name: "Metropolis Shivamogga",
    district: "Shivamogga",
    address: "KDS Layout, Shivamogga",
    phone: "9880800002",
    type: "outside",
    pincode: "577204",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Bhadravathi Lab",
    district: "Shivamogga",
    address: "Bhadravathi, Shivamogga",
    phone: "9880800003",
    type: "outside",
    pincode: "577301",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Jeevan Lab Centre",
    district: "Shivamogga",
    address: "Sagar, Shivamogga",
    phone: "9880800004",
    type: "outside",
    pincode: "577401",
    services: ["X-Ray", "ECG", "Ultrasound"],
  },
  {
    name: "Sahyadri Diagnostics SM",
    district: "Shivamogga",
    address: "Soraba, Shivamogga",
    phone: "9880800005",
    type: "outside",
    pincode: "577429",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Karnataka Diagnostics",
    district: "Shivamogga",
    address: "Thirthahalli, Shivamogga",
    phone: "9880800006",
    type: "outside",
    pincode: "577432",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Vivekananda Lab SM",
    district: "Shivamogga",
    address: "Hosanagara, Shivamogga",
    phone: "9880800007",
    type: "outside",
    pincode: "577418",
    services: ["Stool Test", "Urine Culture"],
  },
  {
    name: "Vijayalakshmi Diagnostics",
    district: "Shivamogga",
    address: "Shikaripura, Shivamogga",
    phone: "9880800008",
    type: "outside",
    pincode: "577427",
    services: ["Blood Culture", "PCR"],
  },
  {
    name: "Ganga Lab Centre",
    district: "Shivamogga",
    address: "Shimoga Old Town",
    phone: "9880800009",
    type: "outside",
    pincode: "577202",
    services: ["Full Body Checkup", "Diabetes Panel"],
  },
  {
    name: "Sparsha Diagnostics",
    district: "Shivamogga",
    address: "Channagiri, Shivamogga",
    phone: "9880800010",
    type: "outside",
    pincode: "577213",
    services: ["Pap Smear", "Allergy Panel"],
  },

  // ─────────────────────────────────────────
  // 9. DAVANGERE
  // ─────────────────────────────────────────
  {
    name: "SRL Diagnostics Davangere",
    district: "Davangere",
    address: "8th Main, Davangere",
    phone: "9880900001",
    type: "outside",
    pincode: "577002",
    services: ["CBC", "Blood Sugar", "Thyroid"],
  },
  {
    name: "Akshaya Diagnostic Centre",
    district: "Davangere",
    address: "PJ Extension, Davangere",
    phone: "9880900002",
    type: "outside",
    pincode: "577002",
    services: ["Liver Function", "Kidney Function"],
  },
  {
    name: "Sai Diagnostic Lab",
    district: "Davangere",
    address: "Vidyanagar, Davangere",
    phone: "9880900003",
    type: "outside",
    pincode: "577005",
    services: ["Lipid Profile", "Vitamin D"],
  },
  {
    name: "City Lab Davangere",
    district: "Davangere",
    address: "Harihar, Davangere",
    phone: "9880900004",
    type: "outside",
    pincode: "577601",
    services: ["X-Ray", "ECG"],
  },
  {
    name: "Nandana Lab",
    district: "Davangere",
    address: "Channagiri Road, Davangere",
    phone: "9880900005",
    type: "outside",
    pincode: "577213",
    services: ["Dengue", "Malaria", "CBC"],
  },
  {
    name: "Jaya Diagnostics",
    district: "Davangere",
    address: "Jagalur, Davangere",
    phone: "9880900006",
    type: "outside",
    pincode: "577528",
    services: ["HbA1c", "Urine Test"],
  },
  {
    name: "Maruthi Lab Centre",
    district: "Davangere",
    address: "Nyamati, Davangere",
    phone: "9880900007",
    type: "outside",
    pincode: "577222",
    services: ["Stool Culture", "Sputum Test"],
  },
  {
    name: "Sapthagiri Lab",
    district: "Davangere",
    address: "Kondajji, Davangere",
    phone: "9880900008",
    type: "outside",
    pincode: "577552",
    services: ["Allergy Panel", "Hormone Panel"],
  },
  {
    name: "Prathima Diagnostics",
    district: "Davangere",
    address: "Holalkere, Davangere",
    phone: "9880900009",
    type: "outside",
    pincode: "577526",
    services: ["Full Body Checkup"],
  },
  {
    name: "Arogya Diagnostic Lab DV",
    district: "Davangere",
    address: "Harihara Road, Davangere",
    phone: "9880900010",
    type: "outside",
    pincode: "577601",
    services: ["Blood Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 10. DHARWAD
  // ─────────────────────────────────────────
  {
    name: "KIMS Diagnostics (Outside)",
    district: "Dharwad",
    address: "Court Circle, Dharwad",
    phone: "9881000001",
    type: "outside",
    pincode: "580001",
    services: ["CBC", "Blood Sugar", "Lipid Profile"],
  },
  {
    name: "Hubli Diagnostic Centre",
    district: "Dharwad",
    address: "Lamington Road, Hubballi",
    phone: "9881000002",
    type: "outside",
    pincode: "580020",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "SRL Diagnostics Hubli",
    district: "Dharwad",
    address: "Vidyanagar, Hubballi",
    phone: "9881000003",
    type: "outside",
    pincode: "580031",
    services: ["Kidney Function", "Vitamin D"],
  },
  {
    name: "Vijaya Diagnostic Dharwad",
    district: "Dharwad",
    address: "Saraswathipuram, Dharwad",
    phone: "9881000004",
    type: "outside",
    pincode: "580002",
    services: ["X-Ray", "Ultrasound", "ECG"],
  },
  {
    name: "Metropolis Hubli",
    district: "Dharwad",
    address: "Keshwapur, Hubballi",
    phone: "9881000005",
    type: "outside",
    pincode: "580023",
    services: ["Full Body Checkup", "Diabetes Panel"],
  },
  {
    name: "Narayana Lab Dharwad",
    district: "Dharwad",
    address: "Kundgol, Dharwad",
    phone: "9881000006",
    type: "outside",
    pincode: "581113",
    services: ["Dengue", "Malaria", "Typhoid"],
  },
  {
    name: "Surya Diagnostic Centre",
    district: "Dharwad",
    address: "Navalgund, Dharwad",
    phone: "9881000007",
    type: "outside",
    pincode: "582208",
    services: ["HbA1c", "Allergy Panel"],
  },
  {
    name: "Basaveshwar Lab",
    district: "Dharwad",
    address: "Kalaghatagi, Dharwad",
    phone: "9881000008",
    type: "outside",
    pincode: "581204",
    services: ["Stool Test", "Urine Culture"],
  },
  {
    name: "Renuka Diagnostics",
    district: "Dharwad",
    address: "Annigeri, Dharwad",
    phone: "9881000009",
    type: "outside",
    pincode: "582208",
    services: ["Pap Smear", "Hormone Panel"],
  },
  {
    name: "Mahadeva Lab Centre",
    district: "Dharwad",
    address: "Shiggaon, Dharwad",
    phone: "9881000010",
    type: "outside",
    pincode: "581205",
    services: ["Blood Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 11. GADAG
  // ─────────────────────────────────────────
  {
    name: "Gadag Diagnostic Lab",
    district: "Gadag",
    address: "Station Road, Gadag",
    phone: "9881100001",
    type: "outside",
    pincode: "582101",
    services: ["CBC", "Blood Sugar"],
  },
  {
    name: "Veeresha Lab Centre",
    district: "Gadag",
    address: "Betgeri, Gadag",
    phone: "9881100002",
    type: "outside",
    pincode: "582102",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Shri Tontadarya Diagnostics",
    district: "Gadag",
    address: "Ron, Gadag",
    phone: "9881100003",
    type: "outside",
    pincode: "582209",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Nrupatunga Lab",
    district: "Gadag",
    address: "Mundargi, Gadag",
    phone: "9881100004",
    type: "outside",
    pincode: "582118",
    services: ["X-Ray", "ECG"],
  },
  {
    name: "Basava Diagnostics Gadag",
    district: "Gadag",
    address: "Shirhatti, Gadag",
    phone: "9881100005",
    type: "outside",
    pincode: "582120",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Parvathi Lab",
    district: "Gadag",
    address: "Naregal, Gadag",
    phone: "9881100006",
    type: "outside",
    pincode: "582119",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Ganga Diagnostic Centre",
    district: "Gadag",
    address: "Nargund, Gadag",
    phone: "9881100007",
    type: "outside",
    pincode: "582207",
    services: ["Ultrasound", "Stool Test"],
  },
  {
    name: "Siddeshwar Lab",
    district: "Gadag",
    address: "Lakshmeshwar, Gadag",
    phone: "9881100008",
    type: "outside",
    pincode: "582116",
    services: ["Allergy Panel", "Full Body Checkup"],
  },
  {
    name: "Yellamma Diagnostics",
    district: "Gadag",
    address: "Rona, Gadag",
    phone: "9881100009",
    type: "outside",
    pincode: "582209",
    services: ["Pap Smear", "CBC"],
  },
  {
    name: "Krupa Lab Gadag",
    district: "Gadag",
    address: "Hulkoti, Gadag",
    phone: "9881100010",
    type: "outside",
    pincode: "582205",
    services: ["Blood Culture", "Urine Culture"],
  },

  // ─────────────────────────────────────────
  // 12. BELAGAVI
  // ─────────────────────────────────────────
  {
    name: "Belgaum Diagnostic Centre",
    district: "Belagavi",
    address: "Tilakwadi, Belagavi",
    phone: "9881200001",
    type: "outside",
    pincode: "590006",
    services: ["CBC", "Blood Sugar", "ECG"],
  },
  {
    name: "SRL Diagnostics Belagavi",
    district: "Belagavi",
    address: "Camp Area, Belagavi",
    phone: "9881200002",
    type: "outside",
    pincode: "590001",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Metropolis Belagavi",
    district: "Belagavi",
    address: "Shahu Nagar, Belagavi",
    phone: "9881200003",
    type: "outside",
    pincode: "590010",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Narayana Lab Belagavi",
    district: "Belagavi",
    address: "Gokak, Belagavi",
    phone: "9881200004",
    type: "outside",
    pincode: "591307",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Savita Diagnostic Lab",
    district: "Belagavi",
    address: "Chikkodi, Belagavi",
    phone: "9881200005",
    type: "outside",
    pincode: "591201",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Vijay Lab Centre BLG",
    district: "Belagavi",
    address: "Raibag, Belagavi",
    phone: "9881200006",
    type: "outside",
    pincode: "591317",
    services: ["HbA1c", "Full Body Checkup"],
  },
  {
    name: "Sankeshwar Lab",
    district: "Belagavi",
    address: "Hukkeri, Belagavi",
    phone: "9881200007",
    type: "outside",
    pincode: "591309",
    services: ["Allergy Panel", "Stool Test"],
  },
  {
    name: "Sharada Diagnostics",
    district: "Belagavi",
    address: "Athani, Belagavi",
    phone: "9881200008",
    type: "outside",
    pincode: "591304",
    services: ["Pap Smear", "Hormone Panel"],
  },
  {
    name: "Mahalaxmi Lab Belagavi",
    district: "Belagavi",
    address: "Bailhongal, Belagavi",
    phone: "9881200009",
    type: "outside",
    pincode: "591102",
    services: ["Blood Culture", "PCR"],
  },
  {
    name: "Renuka Lab Centre BLG",
    district: "Belagavi",
    address: "Saundatti, Belagavi",
    phone: "9881200010",
    type: "outside",
    pincode: "591126",
    services: ["Vitamin D", "Urine Culture"],
  },

  // ─────────────────────────────────────────
  // 13. VIJAYAPURA
  // ─────────────────────────────────────────
  {
    name: "Bijapur Diagnostic Centre",
    district: "Vijayapura",
    address: "Station Road, Vijayapura",
    phone: "9881300001",
    type: "outside",
    pincode: "586101",
    services: ["CBC", "Blood Sugar"],
  },
  {
    name: "Al-Shifa Lab",
    district: "Vijayapura",
    address: "Budhwar Peth, Vijayapura",
    phone: "9881300002",
    type: "outside",
    pincode: "586101",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Basaveshwar Lab VP",
    district: "Vijayapura",
    address: "Sindagi, Vijayapura",
    phone: "9881300003",
    type: "outside",
    pincode: "586128",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Siddheshwar Diagnostics",
    district: "Vijayapura",
    address: "Indi, Vijayapura",
    phone: "9881300004",
    type: "outside",
    pincode: "586209",
    services: ["X-Ray", "ECG"],
  },
  {
    name: "Ganga Lab VP",
    district: "Vijayapura",
    address: "Muddebihal, Vijayapura",
    phone: "9881300005",
    type: "outside",
    pincode: "586212",
    services: ["Dengue", "Malaria", "Widal"],
  },
  {
    name: "Akka Mahadevi Diagnostics",
    district: "Vijayapura",
    address: "Basavana Bagewadi, Vijayapura",
    phone: "9881300006",
    type: "outside",
    pincode: "586203",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Bijapur Path Lab",
    district: "Vijayapura",
    address: "Tikota, Vijayapura",
    phone: "9881300007",
    type: "outside",
    pincode: "586116",
    services: ["Allergy Panel", "Stool Test"],
  },
  {
    name: "Surekha Lab Centre",
    district: "Vijayapura",
    address: "Chadchan, Vijayapura",
    phone: "9881300008",
    type: "outside",
    pincode: "586212",
    services: ["Full Body Checkup"],
  },
  {
    name: "Nirmala Diagnostics VP",
    district: "Vijayapura",
    address: "Talikoti, Vijayapura",
    phone: "9881300009",
    type: "outside",
    pincode: "586214",
    services: ["Blood Culture", "Pap Smear"],
  },
  {
    name: "Sai Datta Lab VP",
    district: "Vijayapura",
    address: "Devar Hippargi, Vijayapura",
    phone: "9881300010",
    type: "outside",
    pincode: "586213",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 14. BAGALKOTE
  // ─────────────────────────────────────────
  {
    name: "Bagalkot Diagnostic Centre",
    district: "Bagalkote",
    address: "Nehru Nagar, Bagalkote",
    phone: "9881400001",
    type: "outside",
    pincode: "587101",
    services: ["CBC", "Blood Sugar", "Thyroid"],
  },
  {
    name: "Chalukya Lab",
    district: "Bagalkote",
    address: "Jamakhandi, Bagalkote",
    phone: "9881400002",
    type: "outside",
    pincode: "587301",
    services: ["Liver Function", "Kidney Function"],
  },
  {
    name: "Malaprabha Diagnostics",
    district: "Bagalkote",
    address: "Mudhol, Bagalkote",
    phone: "9881400003",
    type: "outside",
    pincode: "587313",
    services: ["Lipid Profile", "ECG"],
  },
  {
    name: "Sai Krupa Lab BKT",
    district: "Bagalkote",
    address: "Badami, Bagalkote",
    phone: "9881400004",
    type: "outside",
    pincode: "587201",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Aarush Diagnostics",
    district: "Bagalkote",
    address: "Hungund, Bagalkote",
    phone: "9881400005",
    type: "outside",
    pincode: "587118",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Pattadakal Lab",
    district: "Bagalkote",
    address: "Ilkal, Bagalkote",
    phone: "9881400006",
    type: "outside",
    pincode: "587125",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Ganga Lab BKT",
    district: "Bagalkote",
    address: "Rabkavi, Bagalkote",
    phone: "9881400007",
    type: "outside",
    pincode: "587314",
    services: ["Allergy Panel", "Full Body Checkup"],
  },
  {
    name: "Nrupathunga Lab BKT",
    district: "Bagalkote",
    address: "Bilgi, Bagalkote",
    phone: "9881400008",
    type: "outside",
    pincode: "587116",
    services: ["Pap Smear", "Stool Test"],
  },
  {
    name: "Siddaramaiah Diagnostics",
    district: "Bagalkote",
    address: "Guledgudda, Bagalkote",
    phone: "9881400009",
    type: "outside",
    pincode: "587203",
    services: ["Blood Culture", "Sputum Test"],
  },
  {
    name: "Lakshmi Lab BKT",
    district: "Bagalkote",
    address: "Lokapur, Bagalkote",
    phone: "9881400010",
    type: "outside",
    pincode: "587205",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 15. BALLARI
  // ─────────────────────────────────────────
  {
    name: "Ballari Diagnostic Centre",
    district: "Ballari",
    address: "Cantonment, Ballari",
    phone: "9881500001",
    type: "outside",
    pincode: "583101",
    services: ["CBC", "Blood Sugar", "ECG"],
  },
  {
    name: "Thyrocare Ballari",
    district: "Ballari",
    address: "Gandhi Nagar, Ballari",
    phone: "9881500002",
    type: "outside",
    pincode: "583103",
    services: ["Thyroid", "Full Body Checkup"],
  },
  {
    name: "SRL Diagnostics Ballari",
    district: "Ballari",
    address: "Navabpet, Ballari",
    phone: "9881500003",
    type: "outside",
    pincode: "583101",
    services: ["Liver Function", "Kidney Function"],
  },
  {
    name: "Vijayanagara Lab",
    district: "Ballari",
    address: "Hospet, Ballari",
    phone: "9881500004",
    type: "outside",
    pincode: "583201",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Hampi Diagnostic Lab",
    district: "Ballari",
    address: "Hampi Road, Ballari",
    phone: "9881500005",
    type: "outside",
    pincode: "583239",
    services: ["Dengue", "Malaria", "Typhoid"],
  },
  {
    name: "Akshaya Diagnostics BLR",
    district: "Ballari",
    address: "Siruguppa, Ballari",
    phone: "9881500006",
    type: "outside",
    pincode: "583121",
    services: ["HbA1c", "Lipid Profile"],
  },
  {
    name: "Sangameshwar Lab",
    district: "Ballari",
    address: "Kudligi, Ballari",
    phone: "9881500007",
    type: "outside",
    pincode: "583135",
    services: ["Allergy Panel", "Vitamin D"],
  },
  {
    name: "Nalanda Lab Ballari",
    district: "Ballari",
    address: "Sandur, Ballari",
    phone: "9881500008",
    type: "outside",
    pincode: "583119",
    services: ["Stool Test", "Pap Smear"],
  },
  {
    name: "Renuka Lab BLR",
    district: "Ballari",
    address: "Hadagali, Ballari",
    phone: "9881500009",
    type: "outside",
    pincode: "583130",
    services: ["Blood Culture", "Sputum AFB"],
  },
  {
    name: "Vivekananda Diagnostics BLR",
    district: "Ballari",
    address: "Hagaribommanahalli, Ballari",
    phone: "9881500010",
    type: "outside",
    pincode: "583212",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 16. KOPPAL
  // ─────────────────────────────────────────
  {
    name: "Koppal Diagnostic Lab",
    district: "Koppal",
    address: "Station Road, Koppal",
    phone: "9881600001",
    type: "outside",
    pincode: "583231",
    services: ["CBC", "Blood Sugar"],
  },
  {
    name: "Tungabhadra Diagnostics",
    district: "Koppal",
    address: "Gangavathi, Koppal",
    phone: "9881600002",
    type: "outside",
    pincode: "583227",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Sharada Lab Koppal",
    district: "Koppal",
    address: "Kushtagi, Koppal",
    phone: "9881600003",
    type: "outside",
    pincode: "583225",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Namma Diagnostic Centre",
    district: "Koppal",
    address: "Yelburga, Koppal",
    phone: "9881600004",
    type: "outside",
    pincode: "583236",
    services: ["X-Ray", "ECG"],
  },
  {
    name: "Sai Lab Koppal",
    district: "Koppal",
    address: "Karatagi, Koppal",
    phone: "9881600005",
    type: "outside",
    pincode: "583228",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Basava Lab KPL",
    district: "Koppal",
    address: "Munirabad, Koppal",
    phone: "9881600006",
    type: "outside",
    pincode: "583233",
    services: ["HbA1c", "Full Body Checkup"],
  },
  {
    name: "Lakshmi Lab KPL",
    district: "Koppal",
    address: "Gadag Road, Koppal",
    phone: "9881600007",
    type: "outside",
    pincode: "583231",
    services: ["Ultrasound", "Vitamin D"],
  },
  {
    name: "Priya Diagnostics Koppal",
    district: "Koppal",
    address: "Kustagi Road, Koppal",
    phone: "9881600008",
    type: "outside",
    pincode: "583231",
    services: ["Allergy Panel", "Pap Smear"],
  },
  {
    name: "Jeevan Diagnostics KPL",
    district: "Koppal",
    address: "Itagi, Koppal",
    phone: "9881600009",
    type: "outside",
    pincode: "583220",
    services: ["Blood Culture", "Stool Test"],
  },
  {
    name: "Maruthi Lab KPL",
    district: "Koppal",
    address: "Hirekerur, Koppal",
    phone: "9881600010",
    type: "outside",
    pincode: "581111",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 17. RAICHUR
  // ─────────────────────────────────────────
  {
    name: "Raichur Diagnostic Lab",
    district: "Raichur",
    address: "Civil Lines, Raichur",
    phone: "9881700001",
    type: "outside",
    pincode: "584101",
    services: ["CBC", "Blood Sugar", "ECG"],
  },
  {
    name: "Krishna Diagnostic Centre",
    district: "Raichur",
    address: "Hyderabad Road, Raichur",
    phone: "9881700002",
    type: "outside",
    pincode: "584101",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Manvi Lab Centre",
    district: "Raichur",
    address: "Manvi, Raichur",
    phone: "9881700003",
    type: "outside",
    pincode: "584123",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Shakambari Diagnostics",
    district: "Raichur",
    address: "Sindhanur, Raichur",
    phone: "9881700004",
    type: "outside",
    pincode: "584128",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Sai Lab Raichur",
    district: "Raichur",
    address: "Lingsugur, Raichur",
    phone: "9881700005",
    type: "outside",
    pincode: "584122",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Basaveshwar Lab RC",
    district: "Raichur",
    address: "Devadurga, Raichur",
    phone: "9881700006",
    type: "outside",
    pincode: "584111",
    services: ["HbA1c", "Full Body Checkup"],
  },
  {
    name: "Tungabhadra Lab RC",
    district: "Raichur",
    address: "Maski, Raichur",
    phone: "9881700007",
    type: "outside",
    pincode: "584124",
    services: ["Allergy Panel", "Vitamin D"],
  },
  {
    name: "Giriraj Diagnostics",
    district: "Raichur",
    address: "Mudgal, Raichur",
    phone: "9881700008",
    type: "outside",
    pincode: "584125",
    services: ["Pap Smear", "Stool Test"],
  },
  {
    name: "Pavana Lab RC",
    district: "Raichur",
    address: "Kukanur, Raichur",
    phone: "9881700009",
    type: "outside",
    pincode: "584115",
    services: ["Blood Culture", "Sputum AFB"],
  },
  {
    name: "Vani Diagnostics RC",
    district: "Raichur",
    address: "Shahapur, Raichur",
    phone: "9881700010",
    type: "outside",
    pincode: "585223",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 18. KALABURAGI (GULBARGA)
  // ─────────────────────────────────────────
  {
    name: "Gulbarga Diagnostic Centre",
    district: "Kalaburagi",
    address: "Super Market, Kalaburagi",
    phone: "9881800001",
    type: "outside",
    pincode: "585101",
    services: ["CBC", "Blood Sugar"],
  },
  {
    name: "SRL Diagnostics Kalaburagi",
    district: "Kalaburagi",
    address: "Sedam Road, Kalaburagi",
    phone: "9881800002",
    type: "outside",
    pincode: "585105",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Metropolis Kalaburagi",
    district: "Kalaburagi",
    address: "Jagat, Kalaburagi",
    phone: "9881800003",
    type: "outside",
    pincode: "585101",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Basaveshwar Lab KLB",
    district: "Kalaburagi",
    address: "Afzalpur, Kalaburagi",
    phone: "9881800004",
    type: "outside",
    pincode: "585301",
    services: ["X-Ray", "ECG"],
  },
  {
    name: "Aaditya Diagnostics",
    district: "Kalaburagi",
    address: "Chincholi, Kalaburagi",
    phone: "9881800005",
    type: "outside",
    pincode: "585307",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Shareef Lab",
    district: "Kalaburagi",
    address: "Jewargi, Kalaburagi",
    phone: "9881800006",
    type: "outside",
    pincode: "585310",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Aishwarya Lab KLB",
    district: "Kalaburagi",
    address: "Yadgir Road, Kalaburagi",
    phone: "9881800007",
    type: "outside",
    pincode: "585101",
    services: ["Ultrasound", "Allergy Panel"],
  },
  {
    name: "Narayana Lab KLB",
    district: "Kalaburagi",
    address: "Aland, Kalaburagi",
    phone: "9881800008",
    type: "outside",
    pincode: "585302",
    services: ["Full Body Checkup", "Stool Test"],
  },
  {
    name: "Sai Krupa Diagnostics KLB",
    district: "Kalaburagi",
    address: "Shorapur, Kalaburagi",
    phone: "9881800009",
    type: "outside",
    pincode: "585224",
    services: ["Pap Smear", "Blood Culture"],
  },
  {
    name: "Kavitha Lab KLB",
    district: "Kalaburagi",
    address: "Chittapur, Kalaburagi",
    phone: "9881800010",
    type: "outside",
    pincode: "585211",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 19. BIDAR
  // ─────────────────────────────────────────
  {
    name: "Bidar Diagnostic Lab",
    district: "Bidar",
    address: "Udgir Road, Bidar",
    phone: "9881900001",
    type: "outside",
    pincode: "585401",
    services: ["CBC", "Blood Sugar", "ECG"],
  },
  {
    name: "Kalyani Diagnostics",
    district: "Bidar",
    address: "Old Town, Bidar",
    phone: "9881900002",
    type: "outside",
    pincode: "585401",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Sai Lab Bidar",
    district: "Bidar",
    address: "Bhalki, Bidar",
    phone: "9881900003",
    type: "outside",
    pincode: "585328",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Basaweshwar Diagnostics BD",
    district: "Bidar",
    address: "Basavakalyan, Bidar",
    phone: "9881900004",
    type: "outside",
    pincode: "585327",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Ratna Lab Bidar",
    district: "Bidar",
    address: "Humnabad, Bidar",
    phone: "9881900005",
    type: "outside",
    pincode: "585330",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Indira Lab BD",
    district: "Bidar",
    address: "Aurad, Bidar",
    phone: "9881900006",
    type: "outside",
    pincode: "585326",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Ganga Diagnostic BD",
    district: "Bidar",
    address: "Chitguppa, Bidar",
    phone: "9881900007",
    type: "outside",
    pincode: "585412",
    services: ["Allergy Panel", "Full Body Checkup"],
  },
  {
    name: "Kaveri Lab Bidar",
    district: "Bidar",
    address: "Udgir, Bidar",
    phone: "9881900008",
    type: "outside",
    pincode: "585401",
    services: ["Pap Smear", "Stool Test"],
  },
  {
    name: "Shreya Diagnostics BD",
    district: "Bidar",
    address: "Kamalnagar, Bidar",
    phone: "9881900009",
    type: "outside",
    pincode: "585416",
    services: ["Blood Culture", "Sputum Test"],
  },
  {
    name: "Pavithra Lab BD",
    district: "Bidar",
    address: "Hulsoor, Bidar",
    phone: "9881900010",
    type: "outside",
    pincode: "585403",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 20. YADGIR
  // ─────────────────────────────────────────
  {
    name: "Yadgir Diagnostic Lab",
    district: "Yadgir",
    address: "Main Road, Yadgir",
    phone: "9882000001",
    type: "outside",
    pincode: "585201",
    services: ["CBC", "Blood Sugar"],
  },
  {
    name: "Sharana Diagnostics",
    district: "Yadgir",
    address: "Shorapur, Yadgir",
    phone: "9882000002",
    type: "outside",
    pincode: "585224",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Goutam Lab Yadgir",
    district: "Yadgir",
    address: "Surpur, Yadgir",
    phone: "9882000003",
    type: "outside",
    pincode: "585226",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Basava Diagnostic YD",
    district: "Yadgir",
    address: "Gurumitkal, Yadgir",
    phone: "9882000004",
    type: "outside",
    pincode: "585214",
    services: ["X-Ray", "ECG"],
  },
  {
    name: "Supriya Lab YD",
    district: "Yadgir",
    address: "Hunasagi, Yadgir",
    phone: "9882000005",
    type: "outside",
    pincode: "585216",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Akshaya Lab YD",
    district: "Yadgir",
    address: "Wadagera, Yadgir",
    phone: "9882000006",
    type: "outside",
    pincode: "585227",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Pallavi Diagnostics YD",
    district: "Yadgir",
    address: "Shahpur, Yadgir",
    phone: "9882000007",
    type: "outside",
    pincode: "585223",
    services: ["Allergy Panel", "Full Body Checkup"],
  },
  {
    name: "Sree Lab YD",
    district: "Yadgir",
    address: "Yadgir East, Yadgir",
    phone: "9882000008",
    type: "outside",
    pincode: "585202",
    services: ["Stool Test", "Pap Smear"],
  },
  {
    name: "Amruth Lab YD",
    district: "Yadgir",
    address: "Narona, Yadgir",
    phone: "9882000009",
    type: "outside",
    pincode: "585225",
    services: ["Blood Culture", "Sputum AFB"],
  },
  {
    name: "Jeevan Path Lab YD",
    district: "Yadgir",
    address: "Saidapur, Yadgir",
    phone: "9882000010",
    type: "outside",
    pincode: "585228",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 21. CHITRADURGA
  // ─────────────────────────────────────────
  {
    name: "Chitradurga Diagnostic Lab",
    district: "Chitradurga",
    address: "Fort Road, Chitradurga",
    phone: "9882100001",
    type: "outside",
    pincode: "577501",
    services: ["CBC", "Blood Sugar", "ECG"],
  },
  {
    name: "Vedavathi Lab",
    district: "Chitradurga",
    address: "Holalkere, Chitradurga",
    phone: "9882100002",
    type: "outside",
    pincode: "577526",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Jaya Diagnostics CD",
    district: "Chitradurga",
    address: "Hiriyur, Chitradurga",
    phone: "9882100003",
    type: "outside",
    pincode: "572143",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Sri Sai Lab CD",
    district: "Chitradurga",
    address: "Challakere, Chitradurga",
    phone: "9882100004",
    type: "outside",
    pincode: "577522",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Sudhama Diagnostics",
    district: "Chitradurga",
    address: "Molakalmuru, Chitradurga",
    phone: "9882100005",
    type: "outside",
    pincode: "577535",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Akshaya Diagnostic CD",
    district: "Chitradurga",
    address: "Turuvanur, Chitradurga",
    phone: "9882100006",
    type: "outside",
    pincode: "577501",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Mahalakshmi Lab CD",
    district: "Chitradurga",
    address: "Hosadurga, Chitradurga",
    phone: "9882100007",
    type: "outside",
    pincode: "577527",
    services: ["Allergy Panel", "Full Body Checkup"],
  },
  {
    name: "Sai Balaji Lab CD",
    district: "Chitradurga",
    address: "Parashurampura, Chitradurga",
    phone: "9882100008",
    type: "outside",
    pincode: "577501",
    services: ["Stool Test", "Pap Smear"],
  },
  {
    name: "Surya Lab CD",
    district: "Chitradurga",
    address: "Sirigere, Chitradurga",
    phone: "9882100009",
    type: "outside",
    pincode: "577541",
    services: ["Blood Culture", "Sputum Test"],
  },
  {
    name: "Hanumantha Lab CD",
    district: "Chitradurga",
    address: "Ramagondanahalli, Chitradurga",
    phone: "9882100010",
    type: "outside",
    pincode: "577501",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 22. KODAGU
  // ─────────────────────────────────────────
  {
    name: "Kodagu Diagnostic Centre",
    district: "Kodagu",
    address: "Convent Road, Madikeri",
    phone: "9882200001",
    type: "outside",
    pincode: "571201",
    services: ["CBC", "Blood Sugar"],
  },
  {
    name: "Cauvery Lab Kodagu",
    district: "Kodagu",
    address: "School Road, Madikeri",
    phone: "9882200002",
    type: "outside",
    pincode: "571201",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Malnad Diagnostic Centre",
    district: "Kodagu",
    address: "Virajpet, Kodagu",
    phone: "9882200003",
    type: "outside",
    pincode: "571218",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Coorg Lab Centre",
    district: "Kodagu",
    address: "Kushalnagar, Kodagu",
    phone: "9882200004",
    type: "outside",
    pincode: "571234",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Green Hills Diagnostics",
    district: "Kodagu",
    address: "Ponnampet, Kodagu",
    phone: "9882200005",
    type: "outside",
    pincode: "571216",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Subramanya Lab Kodagu",
    district: "Kodagu",
    address: "Somwarpet, Kodagu",
    phone: "9882200006",
    type: "outside",
    pincode: "571236",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Siri Diagnostics KDG",
    district: "Kodagu",
    address: "Gonikoppal, Kodagu",
    phone: "9882200007",
    type: "outside",
    pincode: "571213",
    services: ["Allergy Panel", "Full Body Checkup"],
  },
  {
    name: "Akash Lab Kodagu",
    district: "Kodagu",
    address: "Kutta, Kodagu",
    phone: "9882200008",
    type: "outside",
    pincode: "571250",
    services: ["Stool Test", "Pap Smear"],
  },
  {
    name: "Holy Cross Lab KDG",
    district: "Kodagu",
    address: "Ammathi, Kodagu",
    phone: "9882200009",
    type: "outside",
    pincode: "571211",
    services: ["Blood Culture", "Sputum AFB"],
  },
  {
    name: "Dwaraka Lab Kodagu",
    district: "Kodagu",
    address: "Napoklu, Kodagu",
    phone: "9882200010",
    type: "outside",
    pincode: "571212",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 23. UDUPI
  // ─────────────────────────────────────────
  {
    name: "Udupi Diagnostic Lab",
    district: "Udupi",
    address: "Car Street, Udupi",
    phone: "9882300001",
    type: "outside",
    pincode: "576101",
    services: ["CBC", "Blood Sugar", "ECG"],
  },
  {
    name: "Sharada Lab Udupi",
    district: "Udupi",
    address: "Manipal, Udupi",
    phone: "9882300002",
    type: "outside",
    pincode: "576104",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Swastha Lab Udupi",
    district: "Udupi",
    address: "Kundapura, Udupi",
    phone: "9882300003",
    type: "outside",
    pincode: "576201",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Namma Lab Udupi",
    district: "Udupi",
    address: "Karkala, Udupi",
    phone: "9882300004",
    type: "outside",
    pincode: "574104",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Sea Shore Diagnostics",
    district: "Udupi",
    address: "Kaup, Udupi",
    phone: "9882300005",
    type: "outside",
    pincode: "574106",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Byndoor Lab",
    district: "Udupi",
    address: "Byndoor, Udupi",
    phone: "9882300006",
    type: "outside",
    pincode: "576214",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Sri Krishna Diagnostics UD",
    district: "Udupi",
    address: "Brahmavar, Udupi",
    phone: "9882300007",
    type: "outside",
    pincode: "576213",
    services: ["Allergy Panel", "Full Body Checkup"],
  },
  {
    name: "Srinivasa Lab Udupi",
    district: "Udupi",
    address: "Shirva, Udupi",
    phone: "9882300008",
    type: "outside",
    pincode: "574116",
    services: ["Stool Test", "Pap Smear"],
  },
  {
    name: "Coastal Diagnostics",
    district: "Udupi",
    address: "Hebri, Udupi",
    phone: "9882300009",
    type: "outside",
    pincode: "576112",
    services: ["Blood Culture", "Sputum Test"],
  },
  {
    name: "Amruth Diagnostic UD",
    district: "Udupi",
    address: "Padubidri, Udupi",
    phone: "9882300010",
    type: "outside",
    pincode: "574115",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 24. DAKSHINA KANNADA
  // ─────────────────────────────────────────
  {
    name: "Mangalore Diagnostic Lab",
    district: "Dakshina Kannada",
    address: "Hampankatta, Mangaluru",
    phone: "9882400001",
    type: "outside",
    pincode: "575001",
    services: ["CBC", "Blood Sugar", "ECG"],
  },
  {
    name: "SRL Diagnostics Mangaluru",
    district: "Dakshina Kannada",
    address: "Kankanady, Mangaluru",
    phone: "9882400002",
    type: "outside",
    pincode: "575002",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Metropolis Mangaluru",
    district: "Dakshina Kannada",
    address: "Bejai, Mangaluru",
    phone: "9882400003",
    type: "outside",
    pincode: "575004",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Thyrocare DK",
    district: "Dakshina Kannada",
    address: "Kadri, Mangaluru",
    phone: "9882400004",
    type: "outside",
    pincode: "575003",
    services: ["Full Body Checkup", "Diabetes Panel"],
  },
  {
    name: "Dr Lal PathLabs DK",
    district: "Dakshina Kannada",
    address: "Pandeshwar, Mangaluru",
    phone: "9882400005",
    type: "outside",
    pincode: "575001",
    services: ["Dengue", "Malaria", "Typhoid"],
  },
  {
    name: "Bantwal Diagnostic Lab",
    district: "Dakshina Kannada",
    address: "Bantwal, DK",
    phone: "9882400006",
    type: "outside",
    pincode: "574219",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Puttur Lab Centre",
    district: "Dakshina Kannada",
    address: "Puttur, DK",
    phone: "9882400007",
    type: "outside",
    pincode: "574201",
    services: ["Allergy Panel", "HbA1c"],
  },
  {
    name: "Belthangady Diagnostics",
    district: "Dakshina Kannada",
    address: "Belthangady, DK",
    phone: "9882400008",
    type: "outside",
    pincode: "574214",
    services: ["Pap Smear", "Stool Test"],
  },
  {
    name: "Sullia Diagnostic Lab",
    district: "Dakshina Kannada",
    address: "Sullia, DK",
    phone: "9882400009",
    type: "outside",
    pincode: "574239",
    services: ["Blood Culture", "Sputum AFB"],
  },
  {
    name: "Manjeshwar Lab DK",
    district: "Dakshina Kannada",
    address: "Manjeshwar, DK",
    phone: "9882400010",
    type: "outside",
    pincode: "671323",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 25. UTTARA KANNADA
  // ─────────────────────────────────────────
  {
    name: "Karwar Diagnostic Lab",
    district: "Uttara Kannada",
    address: "Main Road, Karwar",
    phone: "9882500001",
    type: "outside",
    pincode: "581301",
    services: ["CBC", "Blood Sugar"],
  },
  {
    name: "Kaiga Lab Centre",
    district: "Uttara Kannada",
    address: "Sirsi, UK",
    phone: "9882500002",
    type: "outside",
    pincode: "581401",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Sahyadri Lab UK",
    district: "Uttara Kannada",
    address: "Dandeli, UK",
    phone: "9882500003",
    type: "outside",
    pincode: "581325",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Ankola Diagnostic Lab",
    district: "Uttara Kannada",
    address: "Ankola, UK",
    phone: "9882500004",
    type: "outside",
    pincode: "581314",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Bhatkal Lab Centre",
    district: "Uttara Kannada",
    address: "Bhatkal, UK",
    phone: "9882500005",
    type: "outside",
    pincode: "581320",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Kumta Diagnostic Centre",
    district: "Uttara Kannada",
    address: "Kumta, UK",
    phone: "9882500006",
    type: "outside",
    pincode: "581343",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Honnavar Lab UK",
    district: "Uttara Kannada",
    address: "Honnavar, UK",
    phone: "9882500007",
    type: "outside",
    pincode: "581334",
    services: ["Allergy Panel", "Full Body Checkup"],
  },
  {
    name: "Sagar Diagnostic Lab UK",
    district: "Uttara Kannada",
    address: "Supa, UK",
    phone: "9882500008",
    type: "outside",
    pincode: "581356",
    services: ["Stool Test", "Pap Smear"],
  },
  {
    name: "Yellapur Lab Centre",
    district: "Uttara Kannada",
    address: "Yellapur, UK",
    phone: "9882500009",
    type: "outside",
    pincode: "581359",
    services: ["Blood Culture", "Sputum AFB"],
  },
  {
    name: "Mundgod Diagnostics",
    district: "Uttara Kannada",
    address: "Mundgod, UK",
    phone: "9882500010",
    type: "outside",
    pincode: "581349",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 26. HAVERI
  // ─────────────────────────────────────────
  {
    name: "Haveri Diagnostic Lab",
    district: "Haveri",
    address: "Station Road, Haveri",
    phone: "9882600001",
    type: "outside",
    pincode: "581110",
    services: ["CBC", "Blood Sugar", "ECG"],
  },
  {
    name: "Vani Lab Haveri",
    district: "Haveri",
    address: "Ranebennur, Haveri",
    phone: "9882600002",
    type: "outside",
    pincode: "581115",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Nandana Lab HV",
    district: "Haveri",
    address: "Hirekerur, Haveri",
    phone: "9882600003",
    type: "outside",
    pincode: "581111",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Basaveshwar Lab HV",
    district: "Haveri",
    address: "Byadagi, Haveri",
    phone: "9882600004",
    type: "outside",
    pincode: "581106",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Sai Lab Haveri",
    district: "Haveri",
    address: "Savanur, Haveri",
    phone: "9882600005",
    type: "outside",
    pincode: "581118",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Mahalakshmi Lab HV",
    district: "Haveri",
    address: "Hanagal, Haveri",
    phone: "9882600006",
    type: "outside",
    pincode: "581104",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Kiran Diagnostic Centre HV",
    district: "Haveri",
    address: "Shiggaon, Haveri",
    phone: "9882600007",
    type: "outside",
    pincode: "581205",
    services: ["Allergy Panel", "Full Body Checkup"],
  },
  {
    name: "Krupa Lab HV",
    district: "Haveri",
    address: "Bankapur, Haveri",
    phone: "9882600008",
    type: "outside",
    pincode: "581117",
    services: ["Stool Test", "Pap Smear"],
  },
  {
    name: "Deepa Diagnostics HV",
    district: "Haveri",
    address: "Guttal, Haveri",
    phone: "9882600009",
    type: "outside",
    pincode: "581120",
    services: ["Blood Culture", "Sputum Test"],
  },
  {
    name: "Amruth Lab HV",
    district: "Haveri",
    address: "Motebennur, Haveri",
    phone: "9882600010",
    type: "outside",
    pincode: "581113",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 27. CHIKKABALLAPURA
  // ─────────────────────────────────────────
  {
    name: "Chikkaballapura Diagnostic Lab",
    district: "Chikkaballapura",
    address: "Gandhi Road, Chikkaballapura",
    phone: "9882700001",
    type: "outside",
    pincode: "562101",
    services: ["CBC", "Blood Sugar"],
  },
  {
    name: "Srinivasa Lab CBP",
    district: "Chikkaballapura",
    address: "Gowribidanur, CBP",
    phone: "9882700002",
    type: "outside",
    pincode: "561208",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Gudibande Lab Centre",
    district: "Chikkaballapura",
    address: "Gudibande, CBP",
    phone: "9882700003",
    type: "outside",
    pincode: "561209",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Nandi Hills Lab",
    district: "Chikkaballapura",
    address: "Nandi, CBP",
    phone: "9882700004",
    type: "outside",
    pincode: "562110",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Sidlaghatta Lab",
    district: "Chikkaballapura",
    address: "Sidlaghatta, CBP",
    phone: "9882700005",
    type: "outside",
    pincode: "562105",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Bagepalli Diagnostic Lab",
    district: "Chikkaballapura",
    address: "Bagepalli, CBP",
    phone: "9882700006",
    type: "outside",
    pincode: "561207",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Peresandra Lab CBP",
    district: "Chikkaballapura",
    address: "Peresandra, CBP",
    phone: "9882700007",
    type: "outside",
    pincode: "562101",
    services: ["Allergy Panel", "Full Body Checkup"],
  },
  {
    name: "Shanthi Lab CBP",
    district: "Chikkaballapura",
    address: "Chelur, CBP",
    phone: "9882700008",
    type: "outside",
    pincode: "562101",
    services: ["Stool Test", "Pap Smear"],
  },
  {
    name: "Jyothi Diagnostic CBP",
    district: "Chikkaballapura",
    address: "Kasaba Hobli, CBP",
    phone: "9882700009",
    type: "outside",
    pincode: "562104",
    services: ["Blood Culture", "Sputum AFB"],
  },
  {
    name: "Surabhi Lab CBP",
    district: "Chikkaballapura",
    address: "Shidlaghatta Road, CBP",
    phone: "9882700010",
    type: "outside",
    pincode: "562105",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 28. KOLAR
  // ─────────────────────────────────────────
  {
    name: "Kolar Diagnostic Lab",
    district: "Kolar",
    address: "B B Road, Kolar",
    phone: "9882800001",
    type: "outside",
    pincode: "563101",
    services: ["CBC", "Blood Sugar", "ECG"],
  },
  {
    name: "Gold Fields Lab",
    district: "Kolar",
    address: "KGF, Kolar",
    phone: "9882800002",
    type: "outside",
    pincode: "563115",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Malur Lab Centre",
    district: "Kolar",
    address: "Malur, Kolar",
    phone: "9882800003",
    type: "outside",
    pincode: "563130",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Mulbagal Diagnostic Lab",
    district: "Kolar",
    address: "Mulbagal, Kolar",
    phone: "9882800004",
    type: "outside",
    pincode: "563131",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Bangarpet Lab Centre",
    district: "Kolar",
    address: "Bangarpet, Kolar",
    phone: "9882800005",
    type: "outside",
    pincode: "563114",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Srinivasapura Lab",
    district: "Kolar",
    address: "Srinivasapura, Kolar",
    phone: "9882800006",
    type: "outside",
    pincode: "563135",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Nandi Diagnostics KLR",
    district: "Kolar",
    address: "Nangali, Kolar",
    phone: "9882800007",
    type: "outside",
    pincode: "563101",
    services: ["Allergy Panel", "Full Body Checkup"],
  },
  {
    name: "Sai Shyam Lab KLR",
    district: "Kolar",
    address: "Tayalur, Kolar",
    phone: "9882800008",
    type: "outside",
    pincode: "563102",
    services: ["Stool Test", "Pap Smear"],
  },
  {
    name: "Pavana Lab KLR",
    district: "Kolar",
    address: "Robertsonpet, Kolar",
    phone: "9882800009",
    type: "outside",
    pincode: "563122",
    services: ["Blood Culture", "Sputum Test"],
  },
  {
    name: "Devi Diagnostic KLR",
    district: "Kolar",
    address: "Kolar Town, Kolar",
    phone: "9882800010",
    type: "outside",
    pincode: "563101",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 29. CHAMARAJANAGAR
  // ─────────────────────────────────────────
  {
    name: "Chamarajanagar Diagnostic Lab",
    district: "Chamarajanagar",
    address: "Main Road, Chamarajanagar",
    phone: "9882900001",
    type: "outside",
    pincode: "571313",
    services: ["CBC", "Blood Sugar"],
  },
  {
    name: "Kaveri Diagnostic CJN",
    district: "Chamarajanagar",
    address: "Yelandur, CJN",
    phone: "9882900002",
    type: "outside",
    pincode: "571315",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Kollegal Lab Centre",
    district: "Chamarajanagar",
    address: "Kollegal, CJN",
    phone: "9882900003",
    type: "outside",
    pincode: "571440",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Sargur Diagnostic Lab",
    district: "Chamarajanagar",
    address: "Sargur, CJN",
    phone: "9882900004",
    type: "outside",
    pincode: "571313",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "BRT Lab Centre",
    district: "Chamarajanagar",
    address: "Gundlupet, CJN",
    phone: "9882900005",
    type: "outside",
    pincode: "571111",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Hanur Diagnostic Lab",
    district: "Chamarajanagar",
    address: "Hanur, CJN",
    phone: "9882900006",
    type: "outside",
    pincode: "571439",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Ramapura Lab CJN",
    district: "Chamarajanagar",
    address: "Ramapura, CJN",
    phone: "9882900007",
    type: "outside",
    pincode: "571428",
    services: ["Allergy Panel", "Full Body Checkup"],
  },
  {
    name: "Punjanur Lab Centre",
    district: "Chamarajanagar",
    address: "Punjanur, CJN",
    phone: "9882900008",
    type: "outside",
    pincode: "571490",
    services: ["Stool Test", "Pap Smear"],
  },
  {
    name: "Mahadeshwara Diagnostics",
    district: "Chamarajanagar",
    address: "MM Hills, CJN",
    phone: "9882900009",
    type: "outside",
    pincode: "571490",
    services: ["Blood Culture", "Sputum Test"],
  },
  {
    name: "Forest Edge Lab CJN",
    district: "Chamarajanagar",
    address: "Kuderu, CJN",
    phone: "9882900010",
    type: "outside",
    pincode: "571313",
    services: ["Urine Culture", "PCR"],
  },

  // ─────────────────────────────────────────
  // 30. RAMANAGARA
  // ─────────────────────────────────────────
  {
    name: "Ramanagara Diagnostic Lab",
    district: "Ramanagara",
    address: "Main Road, Ramanagara",
    phone: "9883000001",
    type: "outside",
    pincode: "562159",
    services: ["CBC", "Blood Sugar", "ECG"],
  },
  {
    name: "Channapatna Lab Centre",
    district: "Ramanagara",
    address: "Channapatna, Ramanagara",
    phone: "9883000002",
    type: "outside",
    pincode: "571501",
    services: ["Thyroid", "Liver Function"],
  },
  {
    name: "Magadi Diagnostic Lab",
    district: "Ramanagara",
    address: "Magadi, Ramanagara",
    phone: "9883000003",
    type: "outside",
    pincode: "562120",
    services: ["Kidney Function", "Lipid Profile"],
  },
  {
    name: "Kanakapura Lab",
    district: "Ramanagara",
    address: "Kanakapura, Ramanagara",
    phone: "9883000004",
    type: "outside",
    pincode: "562117",
    services: ["X-Ray", "Ultrasound"],
  },
  {
    name: "Silk City Diagnostics",
    district: "Ramanagara",
    address: "Ramanagara Town",
    phone: "9883000005",
    type: "outside",
    pincode: "562159",
    services: ["Dengue", "Malaria"],
  },
  {
    name: "Sathanur Lab Centre",
    district: "Ramanagara",
    address: "Sathanur, Ramanagara",
    phone: "9883000006",
    type: "outside",
    pincode: "562125",
    services: ["HbA1c", "Vitamin D"],
  },
  {
    name: "Kaveri Lab RNG",
    district: "Ramanagara",
    address: "Bidadi, Ramanagara",
    phone: "9883000007",
    type: "outside",
    pincode: "562109",
    services: ["Allergy Panel", "Full Body Checkup"],
  },
  {
    name: "Namma Diagnostic RNG",
    district: "Ramanagara",
    address: "Harohalli, Ramanagara",
    phone: "9883000008",
    type: "outside",
    pincode: "562112",
    services: ["Stool Test", "Pap Smear"],
  },
  {
    name: "Supriya Lab RNG",
    district: "Ramanagara",
    address: "Manchanabele, Ramanagara",
    phone: "9883000009",
    type: "outside",
    pincode: "562159",
    services: ["Blood Culture", "Sputum Test"],
  },
  {
    name: "Spandana Diagnostic RNG",
    district: "Ramanagara",
    address: "Huliyurdurga, Ramanagara",
    phone: "9883000010",
    type: "outside",
    pincode: "572216",
    services: ["Urine Culture", "PCR"],
  },
];

// ─────────────────────────────────────────────────────────────
// EXPORT & SEED FUNCTION
// ─────────────────────────────────────────────────────────────

/**
 * Usage (Mongoose example):
 *
 * const Lab = require('./models/Lab');
 * const { seedLabs } = require('./seedLab');
 * await seedLabs(Lab);
 */

const seedLabs = async (LabModel) => {
  try {
    await LabModel.deleteMany({ type: "outside" });
    const inserted = await LabModel.insertMany(labs);
    console.log(
      `✅ Seeded ${inserted.length} outside labs across 30 Karnataka districts.`,
    );
  } catch (err) {
    console.error("❌ Seeding failed:", err);
  }
};

module.exports = { labs, seedLabs };
