const mongoose = require("mongoose");
const Hospital = require("./models/hospital");
require("dotenv").config();

const data = [
  // ── BENGALURU URBAN ──────────────────────────────────────
  {
    name: "Manipal Hospital Whitefield",
    address: "Whitefield, Bengaluru",
    city: "Bengaluru",
    type: "Multispeciality",
    rating: 4.8,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Arjun Mehta",
        specialization: "Cardiologist",
        experience: 14,
        available: true,
      },
      {
        name: "Dr. Sunita Rao",
        specialization: "Pediatrician",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Ravi Kumar",
        specialization: "General Physician",
        experience: 6,
        available: false,
      },
      {
        name: "Dr. Priya Nair",
        specialization: "Orthopedic",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Kavitha Sharma",
        specialization: "Dentist",
        experience: 7,
        available: false,
      },
      {
        name: "Dr. Ananya Krishnan",
        specialization: "Dermatologist",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Venkat Raman",
        specialization: "Ophthalmologist",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Ramesh Shenoy",
        specialization: "ENT Specialist",
        experience: 7,
        available: false,
      },
      {
        name: "Dr. Abhijit Rao",
        specialization: "Neurologist",
        experience: 12,
        available: true,
      },
      {
        name: "Dr. Deepak Menon",
        specialization: "Psychiatrist",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Shyam Rao",
        specialization: "Diabetologist",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Arjun Bhat",
        specialization: "Physiotherapist",
        experience: 6,
        available: true,
      },
    ],
  },
  {
    name: "Fortis Hospital Bannerghatta",
    address: "Bannerghatta Road, Bengaluru",
    city: "Bengaluru",
    type: "Multispeciality",
    rating: 4.7,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Ramesh Iyer",
        specialization: "Cardiologist",
        experience: 18,
        available: true,
      },
      {
        name: "Dr. Asha Patel",
        specialization: "General Physician",
        experience: 5,
        available: true,
      },
      {
        name: "Dr. Sunil Reddy",
        specialization: "Orthopedic",
        experience: 12,
        available: false,
      },
      {
        name: "Dr. Meena Krishnan",
        specialization: "Pediatrician",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Rohan Mehta",
        specialization: "Dermatologist",
        experience: 6,
        available: false,
      },
      {
        name: "Dr. Nalini Devi",
        specialization: "Ophthalmologist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Kaveri Nair",
        specialization: "ENT Specialist",
        experience: 5,
        available: true,
      },
      {
        name: "Dr. Swathi Menon",
        specialization: "Neurologist",
        experience: 9,
        available: false,
      },
      {
        name: "Dr. Asha Srinivasan",
        specialization: "Psychiatrist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Kamala Nair",
        specialization: "Diabetologist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Nithya Kumar",
        specialization: "Physiotherapist",
        experience: 4,
        available: false,
      },
    ],
  },
  {
    name: "Narayana Health City",
    address: "Bommasandra, Bengaluru",
    city: "Bengaluru",
    type: "Superspecialty",
    rating: 4.9,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Vikram Shetty",
        specialization: "Cardiologist",
        experience: 22,
        available: true,
      },
      {
        name: "Dr. Divya Menon",
        specialization: "Pediatrician",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Arun Pillai",
        specialization: "Dentist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Neha Gupta",
        specialization: "General Physician",
        experience: 4,
        available: false,
      },
      {
        name: "Dr. Karthik Nair",
        specialization: "Orthopedic",
        experience: 15,
        available: true,
      },
      {
        name: "Dr. Priya Sharma",
        specialization: "Dermatologist",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Prasad Shetty",
        specialization: "Ophthalmologist",
        experience: 11,
        available: false,
      },
      {
        name: "Dr. Sunil Kamath",
        specialization: "ENT Specialist",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Navin Shetty",
        specialization: "Neurologist",
        experience: 14,
        available: true,
      },
      {
        name: "Dr. Vikram Pillai",
        specialization: "Psychiatrist",
        experience: 10,
        available: false,
      },
      {
        name: "Dr. Ramesh Hegde",
        specialization: "Diabetologist",
        experience: 12,
        available: true,
      },
      {
        name: "Dr. Suresh Pillai",
        specialization: "Physiotherapist",
        experience: 8,
        available: true,
      },
    ],
  },
  {
    name: "Bowring & Lady Curzon Hospital",
    address: "Shivajinagar, Bengaluru",
    city: "Bengaluru",
    type: "Government General",
    rating: 4.0,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Girish Babu",
        specialization: "General Physician",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Lakshmi Devi",
        specialization: "Pediatrician",
        experience: 7,
        available: false,
      },
      {
        name: "Dr. Mohan Raj",
        specialization: "Orthopedic",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Suma Kiran",
        specialization: "Dentist",
        experience: 5,
        available: true,
      },
      {
        name: "Dr. Kiran Bhat",
        specialization: "Dermatologist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Suma Bhat",
        specialization: "Ophthalmologist",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Preethi Rao",
        specialization: "ENT Specialist",
        experience: 6,
        available: false,
      },
      {
        name: "Dr. Rekha Pillai",
        specialization: "Neurologist",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Nandini Bhat",
        specialization: "Psychiatrist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Savitha Shetty",
        specialization: "Diabetologist",
        experience: 9,
        available: false,
      },
      {
        name: "Dr. Keerthi Rao",
        specialization: "Physiotherapist",
        experience: 5,
        available: true,
      },
    ],
  },

  // ── MYSURU ───────────────────────────────────────────────
  {
    name: "JSS Hospital Mysuru",
    address: "Agrahara, Mysuru",
    city: "Mysuru",
    type: "Teaching & Multispecialty",
    rating: 4.6,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Pavan Kumar",
        specialization: "Cardiologist",
        experience: 16,
        available: true,
      },
      {
        name: "Dr. Rekha Nayak",
        specialization: "Pediatrician",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Suresh Bhat",
        specialization: "Dentist",
        experience: 11,
        available: false,
      },
      {
        name: "Dr. Anita Rao",
        specialization: "General Physician",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Rajan Verma",
        specialization: "Orthopedic",
        experience: 13,
        available: true,
      },
      {
        name: "Dr. Sunita Joshi",
        specialization: "Dermatologist",
        experience: 9,
        available: false,
      },
      {
        name: "Dr. Girish Nayak",
        specialization: "Ophthalmologist",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Dinesh Bhat",
        specialization: "ENT Specialist",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Satish Nair",
        specialization: "Neurologist",
        experience: 13,
        available: true,
      },
      {
        name: "Dr. Suresh Iyer",
        specialization: "Psychiatrist",
        experience: 9,
        available: false,
      },
      {
        name: "Dr. Girish Pillai",
        specialization: "Diabetologist",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Rajan Nair",
        specialization: "Physiotherapist",
        experience: 7,
        available: false,
      },
    ],
  },
  {
    name: "K R Hospital Mysuru",
    address: "Irwin Road, Mysuru",
    city: "Mysuru",
    type: "Government General",
    rating: 3.9,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Chandra Gowda",
        specialization: "General Physician",
        experience: 12,
        available: true,
      },
      {
        name: "Dr. Usha Kumari",
        specialization: "Pediatrician",
        experience: 9,
        available: false,
      },
      {
        name: "Dr. Bharat Raj",
        specialization: "Orthopedic",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Savitha M",
        specialization: "Dentist",
        experience: 4,
        available: true,
      },
      {
        name: "Dr. Arun Nair",
        specialization: "Dermatologist",
        experience: 5,
        available: true,
      },
      {
        name: "Dr. Rekha Rao",
        specialization: "Ophthalmologist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Sharada Pillai",
        specialization: "ENT Specialist",
        experience: 4,
        available: true,
      },
      {
        name: "Dr. Pooja Kumar",
        specialization: "Neurologist",
        experience: 8,
        available: false,
      },
      {
        name: "Dr. Priya Gowda",
        specialization: "Psychiatrist",
        experience: 5,
        available: true,
      },
      {
        name: "Dr. Usha Kumar",
        specialization: "Diabetologist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Smitha Hegde",
        specialization: "Physiotherapist",
        experience: 3,
        available: true,
      },
    ],
  },
  {
    name: "Columbia Asia Hospital Mysuru",
    address: "Vijayanagar, Mysuru",
    city: "Mysuru",
    type: "Multispeciality",
    rating: 4.5,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Nithya Srinivas",
        specialization: "Cardiologist",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Preetham Rao",
        specialization: "General Physician",
        experience: 5,
        available: true,
      },
      {
        name: "Dr. Keerthi Joshi",
        specialization: "Pediatrician",
        experience: 8,
        available: false,
      },
      {
        name: "Dr. Harish Achar",
        specialization: "Dentist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Deepika Rao",
        specialization: "Dermatologist",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Ashwin Kamath",
        specialization: "Ophthalmologist",
        experience: 12,
        available: false,
      },
      {
        name: "Dr. Arun Gowda",
        specialization: "ENT Specialist",
        experience: 10,
        available: false,
      },
      {
        name: "Dr. Ajay Hegde",
        specialization: "Neurologist",
        experience: 15,
        available: true,
      },
      {
        name: "Dr. Rajesh Nair",
        specialization: "Psychiatrist",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Suresh Menon",
        specialization: "Diabetologist",
        experience: 13,
        available: false,
      },
      {
        name: "Dr. Vinod Shetty",
        specialization: "Physiotherapist",
        experience: 9,
        available: true,
      },
    ],
  },

  // ── DAKSHINA KANNADA ─────────────────────────────────────
  {
    name: "KMC Hospital Mangaluru",
    address: "Ambedkar Circle, Mangaluru",
    city: "Mangaluru",
    type: "Teaching & Multispecialty",
    rating: 4.7,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Sanjay D'Souza",
        specialization: "Cardiologist",
        experience: 20,
        available: true,
      },
      {
        name: "Dr. Reshma Shetty",
        specialization: "Pediatrician",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Alvin Pinto",
        specialization: "Dentist",
        experience: 8,
        available: false,
      },
      {
        name: "Dr. Nagesh Rao",
        specialization: "Orthopedic",
        experience: 15,
        available: true,
      },
      {
        name: "Dr. Flavia Rodrigues",
        specialization: "General Physician",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Meena Reddy",
        specialization: "Dermatologist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Ravi Hegde",
        specialization: "Ophthalmologist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Vikram Hegde",
        specialization: "ENT Specialist",
        experience: 5,
        available: true,
      },
      {
        name: "Dr. Prakash Bhat",
        specialization: "Neurologist",
        experience: 9,
        available: false,
      },
      {
        name: "Dr. Arun Kumar",
        specialization: "Psychiatrist",
        experience: 6,
        available: false,
      },
      {
        name: "Dr. Ravi Iyer",
        specialization: "Diabetologist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Prasad Iyer",
        specialization: "Physiotherapist",
        experience: 4,
        available: true,
      },
    ],
  },
  {
    name: "Wenlock District Hospital",
    address: "Hampankatta, Mangaluru",
    city: "Mangaluru",
    type: "Government General",
    rating: 3.9,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Naveen Kamath",
        specialization: "General Physician",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Sheetal Shetty",
        specialization: "Pediatrician",
        experience: 6,
        available: false,
      },
      {
        name: "Dr. Prasad Hegde",
        specialization: "Orthopedic",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Anupama Bhat",
        specialization: "Dentist",
        experience: 4,
        available: true,
      },
      {
        name: "Dr. Vikram Iyer",
        specialization: "Dermatologist",
        experience: 12,
        available: true,
      },
      {
        name: "Dr. Sheela Pillai",
        specialization: "Ophthalmologist",
        experience: 13,
        available: true,
      },
      {
        name: "Dr. Sindhu Shetty",
        specialization: "ENT Specialist",
        experience: 11,
        available: false,
      },
      {
        name: "Dr. Anupama Reddy",
        specialization: "Neurologist",
        experience: 16,
        available: true,
      },
      {
        name: "Dr. Nalini Gowda",
        specialization: "Diabetologist",
        experience: 14,
        available: true,
      },
      {
        name: "Dr. Shubha Gowda",
        specialization: "Physiotherapist",
        experience: 10,
        available: true,
      },
    ],
  },
  {
    name: "Father Muller Medical College",
    address: "Kankanady, Mangaluru",
    city: "Mangaluru",
    type: "Teaching & Multispecialty",
    rating: 4.5,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Lawrence Pais",
        specialization: "Cardiologist",
        experience: 17,
        available: true,
      },
      {
        name: "Dr. Clara Fernandez",
        specialization: "Pediatrician",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. John Menezes",
        specialization: "General Physician",
        experience: 7,
        available: false,
      },
      {
        name: "Dr. Priya Lobo",
        specialization: "Dentist",
        experience: 5,
        available: true,
      },
      {
        name: "Dr. Shilpa Shetty",
        specialization: "Dermatologist",
        experience: 7,
        available: false,
      },
      {
        name: "Dr. Murali Reddy",
        specialization: "Ophthalmologist",
        experience: 8,
        available: false,
      },
      {
        name: "Dr. Rajendra Naik",
        specialization: "ENT Specialist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Vivek Gowda",
        specialization: "Neurologist",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Harish Hegde",
        specialization: "Psychiatrist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Ashok Naik",
        specialization: "Diabetologist",
        experience: 9,
        available: false,
      },
      {
        name: "Dr. Kiran Naik",
        specialization: "Physiotherapist",
        experience: 5,
        available: false,
      },
    ],
  },

  // ── BELAGAVI ─────────────────────────────────────────────
  {
    name: "KLES Dr Prabhakar Kore Hospital",
    address: "Nehru Nagar, Belagavi",
    city: "Belagavi",
    type: "Teaching & Multispecialty",
    rating: 4.6,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Santosh Patil",
        specialization: "Cardiologist",
        experience: 15,
        available: true,
      },
      {
        name: "Dr. Roopa Desai",
        specialization: "Pediatrician",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Vijay Kulkarni",
        specialization: "Orthopedic",
        experience: 12,
        available: false,
      },
      {
        name: "Dr. Tejashwini Rao",
        specialization: "Dentist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Ashok Joshi",
        specialization: "General Physician",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Padma Hegde",
        specialization: "Dermatologist",
        experience: 5,
        available: true,
      },
      {
        name: "Dr. Sudhir Gowda",
        specialization: "Ophthalmologist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Suresh Bhat",
        specialization: "ENT Specialist",
        experience: 4,
        available: false,
      },
      {
        name: "Dr. Karthik Shetty",
        specialization: "Neurologist",
        experience: 8,
        available: false,
      },
      {
        name: "Dr. Naveen Kamath",
        specialization: "Psychiatrist",
        experience: 5,
        available: true,
      },
      {
        name: "Dr. Mohan Shetty",
        specialization: "Diabetologist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Sunil Rao",
        specialization: "Physiotherapist",
        experience: 3,
        available: true,
      },
    ],
  },
  {
    name: "District Hospital Belagavi",
    address: "Club Road, Belagavi",
    city: "Belagavi",
    type: "Government General",
    rating: 3.8,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Mahesh Goudar",
        specialization: "General Physician",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Kaveri Patil",
        specialization: "Pediatrician",
        experience: 7,
        available: false,
      },
      {
        name: "Dr. Suhas Kambli",
        specialization: "Orthopedic",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Geeta Naik",
        specialization: "Dentist",
        experience: 5,
        available: true,
      },
      {
        name: "Dr. Naveen Gowda",
        specialization: "Dermatologist",
        experience: 10,
        available: false,
      },
      {
        name: "Dr. Parvathi Iyer",
        specialization: "Ophthalmologist",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Vidya Reddy",
        specialization: "ENT Specialist",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Meghna Naik",
        specialization: "Neurologist",
        experience: 14,
        available: true,
      },
      {
        name: "Dr. Lalitha Patil",
        specialization: "Psychiatrist",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Padmini Nair",
        specialization: "Diabetologist",
        experience: 12,
        available: false,
      },
      {
        name: "Dr. Poonam Pillai",
        specialization: "Physiotherapist",
        experience: 8,
        available: false,
      },
    ],
  },

  // ── DHARWAD ──────────────────────────────────────────────
  {
    name: "KIMS Hubli",
    address: "Vidyanagar, Hubli",
    city: "Hubli",
    type: "Teaching & Multispecialty",
    rating: 4.5,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Sudhir Nayak",
        specialization: "Cardiologist",
        experience: 17,
        available: true,
      },
      {
        name: "Dr. Namrata Desai",
        specialization: "Pediatrician",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Aditya Kulkarni",
        specialization: "Orthopedic",
        experience: 12,
        available: false,
      },
      {
        name: "Dr. Vandana Patil",
        specialization: "Dentist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Rishi Joshi",
        specialization: "General Physician",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Usha Nair",
        specialization: "Dermatologist",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Sujatha Kumar",
        specialization: "Ophthalmologist",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Priya Hegde",
        specialization: "ENT Specialist",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Ganesh Rao",
        specialization: "Neurologist",
        experience: 14,
        available: true,
      },
      {
        name: "Dr. Sunil Menon",
        specialization: "Psychiatrist",
        experience: 10,
        available: false,
      },
      {
        name: "Dr. Prakash Rao",
        specialization: "Diabetologist",
        experience: 12,
        available: true,
      },
      {
        name: "Dr. Harish Gowda",
        specialization: "Physiotherapist",
        experience: 8,
        available: true,
      },
    ],
  },

  // ── UDUPI ────────────────────────────────────────────────
  {
    name: "Kasturba Medical College Manipal",
    address: "Madhav Nagar, Manipal",
    city: "Udupi",
    type: "Teaching & Multispecialty",
    rating: 4.9,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Satish Bhat",
        specialization: "Cardiologist",
        experience: 22,
        available: true,
      },
      {
        name: "Dr. Nandini Prabhu",
        specialization: "Pediatrician",
        experience: 12,
        available: true,
      },
      {
        name: "Dr. Anoop Shenoy",
        specialization: "Orthopedic",
        experience: 15,
        available: false,
      },
      {
        name: "Dr. Rashmi Kamath",
        specialization: "Dentist",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Venkatesh Shenoy",
        specialization: "General Physician",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Suresh Pillai",
        specialization: "Dermatologist",
        experience: 8,
        available: false,
      },
      {
        name: "Dr. Divya Kumar",
        specialization: "Ophthalmologist",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Nirmala Kumar",
        specialization: "ENT Specialist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Sudha Iyer",
        specialization: "Neurologist",
        experience: 12,
        available: true,
      },
      {
        name: "Dr. Chitra Rao",
        specialization: "Psychiatrist",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Prabha Bhat",
        specialization: "Diabetologist",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Anuradha Menon",
        specialization: "Physiotherapist",
        experience: 6,
        available: false,
      },
    ],
  },

  // ── HASSAN ───────────────────────────────────────────────
  {
    name: "Hassan Institute of Medical Sciences",
    address: "K R Puram, Hassan",
    city: "Hassan",
    type: "Teaching & Multispecialty",
    rating: 4.3,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Nagabhushana G",
        specialization: "Cardiologist",
        experience: 15,
        available: true,
      },
      {
        name: "Dr. Shyamala K",
        specialization: "Pediatrician",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Chidananda P",
        specialization: "Orthopedic",
        experience: 12,
        available: false,
      },
      {
        name: "Dr. Lalitha R",
        specialization: "Dentist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Somashekar N",
        specialization: "General Physician",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Rajan Kumar",
        specialization: "Dermatologist",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Anita Sharma",
        specialization: "Ophthalmologist",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Gayatri Iyer",
        specialization: "ENT Specialist",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Shilpa Rao",
        specialization: "Neurologist",
        experience: 13,
        available: true,
      },
      {
        name: "Dr. Sushma Reddy",
        specialization: "Psychiatrist",
        experience: 9,
        available: false,
      },
      {
        name: "Dr. Sujatha Rao",
        specialization: "Diabetologist",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Divya Bhat",
        specialization: "Physiotherapist",
        experience: 7,
        available: true,
      },
    ],
  },

  // ── TUMAKURU ─────────────────────────────────────────────
  {
    name: "SS Institute of Medical Sciences Tumakuru",
    address: "NH-4, Tumakuru",
    city: "Tumakuru",
    type: "Teaching & Multispecialty",
    rating: 4.4,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Srinivasa Murthy",
        specialization: "Cardiologist",
        experience: 16,
        available: true,
      },
      {
        name: "Dr. Padmavathi K",
        specialization: "Pediatrician",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Raju Siddappa",
        specialization: "Orthopedic",
        experience: 11,
        available: false,
      },
      {
        name: "Dr. Meghana Raju",
        specialization: "Dentist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Venkatesh D",
        specialization: "General Physician",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Savitha Rao",
        specialization: "Dermatologist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Ambika Bhat",
        specialization: "Ophthalmologist",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Chandra Naik",
        specialization: "ENT Specialist",
        experience: 6,
        available: false,
      },
      {
        name: "Dr. Srikanth Gowda",
        specialization: "Neurologist",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Ranjit Gowda",
        specialization: "Psychiatrist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Mahesh Gowda",
        specialization: "Diabetologist",
        experience: 9,
        available: false,
      },
      {
        name: "Dr. Deepak Pillai",
        specialization: "Physiotherapist",
        experience: 5,
        available: true,
      },
    ],
  },

  // ── SHIVAMOGGA ───────────────────────────────────────────
  {
    name: "McGann District Hospital",
    address: "Shivamogga Town",
    city: "Shivamogga",
    type: "Government General",
    rating: 3.9,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Suresh Naik",
        specialization: "General Physician",
        experience: 12,
        available: true,
      },
      {
        name: "Dr. Geetha Sagar",
        specialization: "Pediatrician",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Manjunath Hegde",
        specialization: "Orthopedic",
        experience: 10,
        available: false,
      },
      {
        name: "Dr. Shruthi Rao",
        specialization: "Dentist",
        experience: 5,
        available: true,
      },
      {
        name: "Dr. Anil Kumar N",
        specialization: "Cardiologist",
        experience: 14,
        available: true,
      },
      {
        name: "Dr. Kiran Bhat",
        specialization: "Dermatologist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Suma Bhat",
        specialization: "Ophthalmologist",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Preethi Rao",
        specialization: "ENT Specialist",
        experience: 6,
        available: false,
      },
      {
        name: "Dr. Rekha Pillai",
        specialization: "Neurologist",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Nandini Bhat",
        specialization: "Psychiatrist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Savitha Shetty",
        specialization: "Diabetologist",
        experience: 9,
        available: false,
      },
      {
        name: "Dr. Keerthi Rao",
        specialization: "Physiotherapist",
        experience: 5,
        available: true,
      },
    ],
  },

  // ── KALABURAGI ───────────────────────────────────────────
  {
    name: "ESIC Medical College Kalaburagi",
    address: "Sedam Road, Kalaburagi",
    city: "Kalaburagi",
    type: "Teaching & Multispecialty",
    rating: 4.2,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Shiva Prasad",
        specialization: "General Physician",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Rani Patil",
        specialization: "Pediatrician",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Manjunath Reddy",
        specialization: "Orthopedic",
        experience: 13,
        available: false,
      },
      {
        name: "Dr. Swapna Goud",
        specialization: "Dentist",
        experience: 5,
        available: true,
      },
      {
        name: "Dr. Kavitha Bhat",
        specialization: "Dermatologist",
        experience: 11,
        available: false,
      },
      {
        name: "Dr. Kiran Rao",
        specialization: "Ophthalmologist",
        experience: 12,
        available: true,
      },
      {
        name: "Dr. Kishore Patil",
        specialization: "ENT Specialist",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Arvind Kumar",
        specialization: "Neurologist",
        experience: 15,
        available: true,
      },
      {
        name: "Dr. Sanjay Rao",
        specialization: "Psychiatrist",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Dinesh Kumar",
        specialization: "Diabetologist",
        experience: 13,
        available: true,
      },
      {
        name: "Dr. Ravi Hegde",
        specialization: "Physiotherapist",
        experience: 9,
        available: false,
      },
    ],
  },

  // ── RAICHUR ──────────────────────────────────────────────
  {
    name: "Raichur Institute of Medical Sciences",
    address: "Hyderabad Road, Raichur",
    city: "Raichur",
    type: "Teaching & Multispecialty",
    rating: 4.2,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Sateesh Reddy",
        specialization: "Cardiologist",
        experience: 14,
        available: true,
      },
      {
        name: "Dr. Sudha Bai",
        specialization: "Pediatrician",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Mallikarjun G",
        specialization: "Orthopedic",
        experience: 11,
        available: false,
      },
      {
        name: "Dr. Kavya Nayak",
        specialization: "Dentist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Ramana Murthy",
        specialization: "General Physician",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Mohan Kamath",
        specialization: "Dermatologist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Smitha Nair",
        specialization: "Ophthalmologist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Anusha Rao",
        specialization: "ENT Specialist",
        experience: 5,
        available: false,
      },
      {
        name: "Dr. Nandita Bhat",
        specialization: "Neurologist",
        experience: 9,
        available: false,
      },
      {
        name: "Dr. Roopa Bhat",
        specialization: "Psychiatrist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Rekha Hegde",
        specialization: "Diabetologist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Geetha Kumar",
        specialization: "Physiotherapist",
        experience: 4,
        available: true,
      },
    ],
  },

  // ── BALLARI ──────────────────────────────────────────────
  {
    name: "Vijayanagara Institute of Medical Sciences",
    address: "Camp Area, Ballari",
    city: "Ballari",
    type: "Teaching & Multispecialty",
    rating: 4.3,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Suresh Kumar B",
        specialization: "Cardiologist",
        experience: 16,
        available: true,
      },
      {
        name: "Dr. Nalini Devi",
        specialization: "Pediatrician",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Raju Naidu",
        specialization: "Orthopedic",
        experience: 13,
        available: false,
      },
      {
        name: "Dr. Sunitha Bai",
        specialization: "Dentist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Venkataramu N",
        specialization: "General Physician",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Rajesh Shenoy",
        specialization: "Dermatologist",
        experience: 5,
        available: false,
      },
      {
        name: "Dr. Anil Patil",
        specialization: "Ophthalmologist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Ratna Gowda",
        specialization: "ENT Specialist",
        experience: 4,
        available: true,
      },
      {
        name: "Dr. Priya Nair",
        specialization: "Neurologist",
        experience: 8,
        available: false,
      },
      {
        name: "Dr. Gayatri Kumar",
        specialization: "Psychiatrist",
        experience: 5,
        available: true,
      },
      {
        name: "Dr. Geetha Menon",
        specialization: "Diabetologist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Kavitha Iyer",
        specialization: "Physiotherapist",
        experience: 3,
        available: false,
      },
    ],
  },

  // ── VIJAYAPURA ───────────────────────────────────────────
  {
    name: "BLDE University Shri BM Patil Hospital",
    address: "Bijapur Road, Vijayapura",
    city: "Vijayapura",
    type: "Teaching & Multispecialty",
    rating: 4.4,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Ashok Patil V",
        specialization: "Cardiologist",
        experience: 17,
        available: true,
      },
      {
        name: "Dr. Pushpa Desai",
        specialization: "Pediatrician",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Ravi Shankar K",
        specialization: "Orthopedic",
        experience: 13,
        available: false,
      },
      {
        name: "Dr. Asha Kulkarni",
        specialization: "Dentist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Bheemashankar",
        specialization: "General Physician",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Harish Kumar",
        specialization: "Dermatologist",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Vijay Rao",
        specialization: "Ophthalmologist",
        experience: 12,
        available: true,
      },
      {
        name: "Dr. Ravi Patil",
        specialization: "ENT Specialist",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Uma Iyer",
        specialization: "Neurologist",
        experience: 15,
        available: true,
      },
      {
        name: "Dr. Sudha Iyer",
        specialization: "Psychiatrist",
        experience: 11,
        available: false,
      },
      {
        name: "Dr. Deepa Shetty",
        specialization: "Diabetologist",
        experience: 13,
        available: true,
      },
      {
        name: "Dr. Uma Rao",
        specialization: "Physiotherapist",
        experience: 9,
        available: true,
      },
    ],
  },

  // ── DAVANAGERE ───────────────────────────────────────────
  {
    name: "SS Institute of Medical Sciences Davangere",
    address: "MCC B Block, Davanagere",
    city: "Davanagere",
    type: "Teaching & Multispecialty",
    rating: 4.4,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Sadashiv Rao",
        specialization: "Cardiologist",
        experience: 18,
        available: true,
      },
      {
        name: "Dr. Sharada Bhat",
        specialization: "Pediatrician",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Rajanna P",
        specialization: "Orthopedic",
        experience: 13,
        available: false,
      },
      {
        name: "Dr. Pushpalatha K",
        specialization: "Dentist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Ashok Kumar D",
        specialization: "General Physician",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Shilpa Shetty",
        specialization: "Dermatologist",
        experience: 7,
        available: false,
      },
      {
        name: "Dr. Murali Reddy",
        specialization: "Ophthalmologist",
        experience: 8,
        available: false,
      },
      {
        name: "Dr. Rajendra Naik",
        specialization: "ENT Specialist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Vivek Gowda",
        specialization: "Neurologist",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Harish Hegde",
        specialization: "Psychiatrist",
        experience: 7,
        available: true,
      },
      {
        name: "Dr. Ashok Naik",
        specialization: "Diabetologist",
        experience: 9,
        available: false,
      },
      {
        name: "Dr. Kiran Naik",
        specialization: "Physiotherapist",
        experience: 5,
        available: false,
      },
    ],
  },

  // ── BIDAR ────────────────────────────────────────────────
  {
    name: "Bidar Institute of Medical Sciences",
    address: "Udgir Road, Bidar",
    city: "Bidar",
    type: "Teaching & Multispecialty",
    rating: 4.1,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Shivraj Patil",
        specialization: "Cardiologist",
        experience: 15,
        available: true,
      },
      {
        name: "Dr. Shobha Kulkarni",
        specialization: "Pediatrician",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Ramesh Kamble",
        specialization: "Orthopedic",
        experience: 12,
        available: false,
      },
      {
        name: "Dr. Priya Ambedkar",
        specialization: "Dentist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Siddharth Patil",
        specialization: "General Physician",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Vikram Iyer",
        specialization: "Dermatologist",
        experience: 12,
        available: true,
      },
      {
        name: "Dr. Sheela Pillai",
        specialization: "Ophthalmologist",
        experience: 13,
        available: true,
      },
      {
        name: "Dr. Sindhu Shetty",
        specialization: "ENT Specialist",
        experience: 11,
        available: false,
      },
      {
        name: "Dr. Anupama Reddy",
        specialization: "Neurologist",
        experience: 16,
        available: true,
      },
      {
        name: "Dr. Nalini Gowda",
        specialization: "Diabetologist",
        experience: 14,
        available: true,
      },
      {
        name: "Dr. Shubha Gowda",
        specialization: "Physiotherapist",
        experience: 10,
        available: true,
      },
    ],
  },

  // ── MANDYA ───────────────────────────────────────────────
  {
    name: "Mandya Institute of Medical Sciences",
    address: "Mandya Town",
    city: "Mandya",
    type: "Teaching & Multispecialty",
    rating: 4.2,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Krishnamurthy S",
        specialization: "Cardiologist",
        experience: 15,
        available: true,
      },
      {
        name: "Dr. Shobha Rajan",
        specialization: "Pediatrician",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Nagaraju M",
        specialization: "Orthopedic",
        experience: 12,
        available: false,
      },
      {
        name: "Dr. Sumana K",
        specialization: "Dentist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Ramachandra Gowda",
        specialization: "General Physician",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Deepika Rao",
        specialization: "Dermatologist",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Ashwin Kamath",
        specialization: "Ophthalmologist",
        experience: 12,
        available: false,
      },
      {
        name: "Dr. Arun Gowda",
        specialization: "ENT Specialist",
        experience: 10,
        available: false,
      },
      {
        name: "Dr. Ajay Hegde",
        specialization: "Neurologist",
        experience: 15,
        available: true,
      },
      {
        name: "Dr. Rajesh Nair",
        specialization: "Psychiatrist",
        experience: 11,
        available: true,
      },
      {
        name: "Dr. Suresh Menon",
        specialization: "Diabetologist",
        experience: 13,
        available: false,
      },
      {
        name: "Dr. Vinod Shetty",
        specialization: "Physiotherapist",
        experience: 9,
        available: true,
      },
    ],
  },

  // ── KOLAR ────────────────────────────────────────────────
  {
    name: "Vydehi Institute Kolar",
    address: "Whitefield Road, Kolar",
    city: "Kolar",
    type: "Teaching & Multispecialty",
    rating: 4.3,
    status: "approved",
    isActive: true,
    doctors: [
      {
        name: "Dr. Padmapriya G",
        specialization: "Cardiologist",
        experience: 13,
        available: true,
      },
      {
        name: "Dr. Suresh Gowda K",
        specialization: "Pediatrician",
        experience: 8,
        available: true,
      },
      {
        name: "Dr. Manohar Rao",
        specialization: "Orthopedic",
        experience: 11,
        available: false,
      },
      {
        name: "Dr. Nalini Srinivasan",
        specialization: "Dentist",
        experience: 6,
        available: true,
      },
      {
        name: "Dr. Ravi Chandran",
        specialization: "General Physician",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Priya Sharma",
        specialization: "Dermatologist",
        experience: 10,
        available: true,
      },
      {
        name: "Dr. Prasad Shetty",
        specialization: "Ophthalmologist",
        experience: 11,
        available: false,
      },
      {
        name: "Dr. Sunil Kamath",
        specialization: "ENT Specialist",
        experience: 9,
        available: true,
      },
      {
        name: "Dr. Navin Shetty",
        specialization: "Neurologist",
        experience: 14,
        available: true,
      },
      {
        name: "Dr. Vikram Pillai",
        specialization: "Psychiatrist",
        experience: 10,
        available: false,
      },
      {
        name: "Dr. Ramesh Hegde",
        specialization: "Diabetologist",
        experience: 12,
        available: true,
      },
      {
        name: "Dr. Suresh Pillai",
        specialization: "Physiotherapist",
        experience: 8,
        available: true,
      },
    ],
  },
];

mongoose
  .connect(process.env.MONGO_URI)
  .then(async () => {
    console.log("MongoDB connected ✅");
    await Hospital.deleteMany({ status: "approved", adminEmail: "" });
    await Hospital.insertMany(data);
    console.log(`✅ ${data.length} hospitals seeded successfully!`);
    process.exit();
  })
  .catch((err) => {
    console.log("❌ Error:", err);
    process.exit(1);
  });
