// src/features/medicine/seedMedicine.js
// Seed data — Categories → Medicines

const seedMedicines = [
  // ─────────────────────────────────────────
  // 1. PAIN RELIEF
  // ─────────────────────────────────────────
  {
    category: "Pain Relief",
    icon: "💊",
    color: "#E24B4A",
    colorLight: "#FCEBEB",
    medicines: [
      {
        id: "m1",
        name: "Paracetamol 500mg",
        brand: "Calpol",
        price: 28,
        mrp: 35,
        unit: "Strip of 10",
        stock: true,
        prescription: false,
        description: "Effective for fever and mild to moderate pain relief.",
        image: "💊",
      },
      {
        id: "m2",
        name: "Ibuprofen 400mg",
        brand: "Brufen",
        price: 42,
        mrp: 52,
        unit: "Strip of 10",
        stock: true,
        prescription: false,
        description:
          "Anti-inflammatory pain reliever for headache, toothache and muscle pain.",
        image: "💊",
      },
      {
        id: "m3",
        name: "Diclofenac 50mg",
        brand: "Voveran",
        price: 55,
        mrp: 68,
        unit: "Strip of 10",
        stock: true,
        prescription: true,
        description: "Used for arthritis, menstrual cramps and acute pain.",
        image: "💊",
      },
      {
        id: "m4",
        name: "Aspirin 75mg",
        brand: "Ecosprin",
        price: 18,
        mrp: 22,
        unit: "Strip of 14",
        stock: true,
        prescription: false,
        description: "Low-dose aspirin for heart health and pain relief.",
        image: "💊",
      },
      {
        id: "m5",
        name: "Tramadol 50mg",
        brand: "Contramal",
        price: 120,
        mrp: 145,
        unit: "Strip of 10",
        stock: false,
        prescription: true,
        description: "Strong opioid pain reliever for moderate to severe pain.",
        image: "💊",
      },
    ],
  },

  // ─────────────────────────────────────────
  // 2. ANTIBIOTICS
  // ─────────────────────────────────────────
  {
    category: "Antibiotics",
    icon: "🧬",
    color: "#185FA5",
    colorLight: "#E6F1FB",
    medicines: [
      {
        id: "m6",
        name: "Amoxicillin 500mg",
        brand: "Mox",
        price: 85,
        mrp: 105,
        unit: "Strip of 10",
        stock: true,
        prescription: true,
        description: "Broad-spectrum antibiotic for bacterial infections.",
        image: "🧬",
      },
      {
        id: "m7",
        name: "Azithromycin 500mg",
        brand: "Azee",
        price: 95,
        mrp: 115,
        unit: "Strip of 5",
        stock: true,
        prescription: true,
        description: "Used for respiratory tract, skin and ear infections.",
        image: "🧬",
      },
      {
        id: "m8",
        name: "Ciprofloxacin 500mg",
        brand: "Cifran",
        price: 78,
        mrp: 95,
        unit: "Strip of 10",
        stock: true,
        prescription: true,
        description: "Effective against urinary tract and gut infections.",
        image: "🧬",
      },
      {
        id: "m9",
        name: "Metronidazole 400mg",
        brand: "Flagyl",
        price: 32,
        mrp: 40,
        unit: "Strip of 15",
        stock: true,
        prescription: true,
        description: "Used for bacterial and parasitic infections.",
        image: "🧬",
      },
      {
        id: "m10",
        name: "Doxycycline 100mg",
        brand: "Doxt",
        price: 62,
        mrp: 78,
        unit: "Strip of 10",
        stock: false,
        prescription: true,
        description: "Treats acne, chest infections and Lyme disease.",
        image: "🧬",
      },
    ],
  },

  // ─────────────────────────────────────────
  // 3. VITAMINS & SUPPLEMENTS
  // ─────────────────────────────────────────
  {
    category: "Vitamins & Supplements",
    icon: "🌿",
    color: "#0D9E75",
    colorLight: "#E1F5EE",
    medicines: [
      {
        id: "m11",
        name: "Vitamin C 500mg",
        brand: "Limcee",
        price: 45,
        mrp: 55,
        unit: "Strip of 15",
        stock: true,
        prescription: false,
        description: "Boosts immunity and fights free radicals.",
        image: "🌿",
      },
      {
        id: "m12",
        name: "Vitamin D3 60000 IU",
        brand: "D-Rise",
        price: 110,
        mrp: 135,
        unit: "Pack of 4",
        stock: true,
        prescription: false,
        description: "Supports bone health and immune function.",
        image: "🌿",
      },
      {
        id: "m13",
        name: "Multivitamin Daily",
        brand: "Supradyn",
        price: 185,
        mrp: 220,
        unit: "Strip of 15",
        stock: true,
        prescription: false,
        description: "Complete daily multivitamin with minerals.",
        image: "🌿",
      },
      {
        id: "m14",
        name: "Omega-3 Fatty Acids",
        brand: "Salmon Oil",
        price: 320,
        mrp: 390,
        unit: "Bottle 60 caps",
        stock: true,
        prescription: false,
        description: "Supports heart, brain and joint health.",
        image: "🌿",
      },
      {
        id: "m15",
        name: "Iron + Folic Acid",
        brand: "Fefol",
        price: 58,
        mrp: 72,
        unit: "Strip of 30",
        stock: true,
        prescription: false,
        description: "Treats iron deficiency anaemia.",
        image: "🌿",
      },
    ],
  },

  // ─────────────────────────────────────────
  // 4. CARDIAC & BP
  // ─────────────────────────────────────────
  {
    category: "Cardiac & BP",
    icon: "❤️",
    color: "#E24B4A",
    colorLight: "#FCEBEB",
    medicines: [
      {
        id: "m16",
        name: "Amlodipine 5mg",
        brand: "Amlong",
        price: 38,
        mrp: 48,
        unit: "Strip of 15",
        stock: true,
        prescription: true,
        description: "Calcium channel blocker for high blood pressure.",
        image: "❤️",
      },
      {
        id: "m17",
        name: "Atorvastatin 10mg",
        brand: "Atorva",
        price: 65,
        mrp: 80,
        unit: "Strip of 15",
        stock: true,
        prescription: true,
        description: "Lowers LDL cholesterol levels.",
        image: "❤️",
      },
      {
        id: "m18",
        name: "Metoprolol 25mg",
        brand: "Metolar",
        price: 42,
        mrp: 52,
        unit: "Strip of 15",
        stock: true,
        prescription: true,
        description: "Beta-blocker for heart rate and BP control.",
        image: "❤️",
      },
      {
        id: "m19",
        name: "Losartan 50mg",
        brand: "Losartan",
        price: 55,
        mrp: 68,
        unit: "Strip of 15",
        stock: false,
        prescription: true,
        description: "ARB for hypertension and kidney protection.",
        image: "❤️",
      },
      {
        id: "m20",
        name: "Clopidogrel 75mg",
        brand: "Clopivas",
        price: 88,
        mrp: 108,
        unit: "Strip of 15",
        stock: true,
        prescription: true,
        description: "Blood thinner to prevent heart attack and stroke.",
        image: "❤️",
      },
    ],
  },

  // ─────────────────────────────────────────
  // 5. DIABETES
  // ─────────────────────────────────────────
  {
    category: "Diabetes",
    icon: "🩸",
    color: "#BA7517",
    colorLight: "#FAEEDA",
    medicines: [
      {
        id: "m21",
        name: "Metformin 500mg",
        brand: "Glycomet",
        price: 32,
        mrp: 40,
        unit: "Strip of 20",
        stock: true,
        prescription: true,
        description: "First-line treatment for type 2 diabetes.",
        image: "🩸",
      },
      {
        id: "m22",
        name: "Glimepiride 1mg",
        brand: "Amaryl",
        price: 48,
        mrp: 60,
        unit: "Strip of 30",
        stock: true,
        prescription: true,
        description: "Sulfonylurea to lower blood glucose.",
        image: "🩸",
      },
      {
        id: "m23",
        name: "Insulin Glargine",
        brand: "Lantus",
        price: 850,
        mrp: 1020,
        unit: "1 Pen",
        stock: true,
        prescription: true,
        description: "Long-acting basal insulin for diabetes.",
        image: "🩸",
      },
      {
        id: "m24",
        name: "Sitagliptin 100mg",
        brand: "Januvia",
        price: 420,
        mrp: 510,
        unit: "Strip of 14",
        stock: false,
        prescription: true,
        description: "DPP-4 inhibitor for type 2 diabetes.",
        image: "🩸",
      },
      {
        id: "m25",
        name: "Empagliflozin 10mg",
        brand: "Jardiance",
        price: 580,
        mrp: 710,
        unit: "Strip of 10",
        stock: true,
        prescription: true,
        description:
          "SGLT2 inhibitor for glucose control and heart protection.",
        image: "🩸",
      },
    ],
  },

  // ─────────────────────────────────────────
  // 6. COLD & COUGH
  // ─────────────────────────────────────────
  {
    category: "Cold & Cough",
    icon: "🤧",
    color: "#534AB7",
    colorLight: "#EEEDFE",
    medicines: [
      {
        id: "m26",
        name: "Cetirizine 10mg",
        brand: "Zyrtec",
        price: 22,
        mrp: 28,
        unit: "Strip of 10",
        stock: true,
        prescription: false,
        description: "Antihistamine for allergy, runny nose and sneezing.",
        image: "🤧",
      },
      {
        id: "m27",
        name: "Montelukast 10mg",
        brand: "Montair",
        price: 68,
        mrp: 85,
        unit: "Strip of 10",
        stock: true,
        prescription: true,
        description: "Used for asthma and seasonal allergies.",
        image: "🤧",
      },
      {
        id: "m28",
        name: "Salbutamol Inhaler",
        brand: "Asthalin",
        price: 95,
        mrp: 118,
        unit: "1 Inhaler",
        stock: true,
        prescription: true,
        description: "Quick-relief bronchodilator for asthma.",
        image: "🤧",
      },
      {
        id: "m29",
        name: "Dextromethorphan Syrup",
        brand: "Benylin",
        price: 75,
        mrp: 92,
        unit: "100ml bottle",
        stock: true,
        prescription: false,
        description: "Cough suppressant for dry cough.",
        image: "🤧",
      },
      {
        id: "m30",
        name: "Ambroxol 30mg",
        brand: "Mucosolvan",
        price: 38,
        mrp: 48,
        unit: "Strip of 10",
        stock: true,
        prescription: false,
        description: "Mucolytic agent to loosen chest mucus.",
        image: "🤧",
      },
    ],
  },

  // ─────────────────────────────────────────
  // 7. SKIN CARE
  // ─────────────────────────────────────────
  {
    category: "Skin Care",
    icon: "🧴",
    color: "#D85A30",
    colorLight: "#FAECE7",
    medicines: [
      {
        id: "m31",
        name: "Clotrimazole Cream 1%",
        brand: "Candid",
        price: 48,
        mrp: 60,
        unit: "30g tube",
        stock: true,
        prescription: false,
        description: "Antifungal cream for ringworm and athlete's foot.",
        image: "🧴",
      },
      {
        id: "m32",
        name: "Betamethasone Cream",
        brand: "Betnovate",
        price: 55,
        mrp: 68,
        unit: "20g tube",
        stock: true,
        prescription: true,
        description: "Steroid cream for eczema and skin inflammation.",
        image: "🧴",
      },
      {
        id: "m33",
        name: "Calamine Lotion",
        brand: "Lacto",
        price: 65,
        mrp: 80,
        unit: "100ml bottle",
        stock: true,
        prescription: false,
        description: "Soothes itching, rashes and sunburn.",
        image: "🧴",
      },
      {
        id: "m34",
        name: "Adapalene Gel 0.1%",
        brand: "Deriva",
        price: 180,
        mrp: 220,
        unit: "15g tube",
        stock: true,
        prescription: true,
        description: "Retinoid gel for acne treatment.",
        image: "🧴",
      },
      {
        id: "m35",
        name: "Mupirocin Ointment 2%",
        brand: "T-Bact",
        price: 95,
        mrp: 118,
        unit: "5g tube",
        stock: false,
        prescription: true,
        description: "Antibiotic ointment for skin infections.",
        image: "🧴",
      },
    ],
  },

  // ─────────────────────────────────────────
  // 8. DIGESTIVE HEALTH
  // ─────────────────────────────────────────
  {
    category: "Digestive Health",
    icon: "🫃",
    color: "#0D9E75",
    colorLight: "#E1F5EE",
    medicines: [
      {
        id: "m36",
        name: "Pantoprazole 40mg",
        brand: "Pan",
        price: 42,
        mrp: 52,
        unit: "Strip of 15",
        stock: true,
        prescription: false,
        description: "Proton pump inhibitor for acidity and GERD.",
        image: "🫃",
      },
      {
        id: "m37",
        name: "Omeprazole 20mg",
        brand: "Omez",
        price: 38,
        mrp: 48,
        unit: "Strip of 15",
        stock: true,
        prescription: false,
        description: "Reduces stomach acid for ulcers and heartburn.",
        image: "🫃",
      },
      {
        id: "m38",
        name: "Domperidone 10mg",
        brand: "Domstal",
        price: 28,
        mrp: 35,
        unit: "Strip of 10",
        stock: true,
        prescription: false,
        description: "Anti-nausea medicine for vomiting and bloating.",
        image: "🫃",
      },
      {
        id: "m39",
        name: "Loperamide 2mg",
        brand: "Imodium",
        price: 35,
        mrp: 44,
        unit: "Strip of 6",
        stock: true,
        prescription: false,
        description: "Fast relief from diarrhoea.",
        image: "🫃",
      },
      {
        id: "m40",
        name: "Lactobacillus Capsules",
        brand: "Sporolac",
        price: 65,
        mrp: 80,
        unit: "Strip of 20",
        stock: true,
        prescription: false,
        description: "Probiotic for gut health and digestion.",
        image: "🫃",
      },
    ],
  },
];

export default seedMedicines;
